import { Challenge } from "./types";

// Mock data for challenges
export const challenges: Challenge[] = [
  {
    id: 1,
    title: "Cardio 30 Day Challenge",
    duration: 30,
    description: "A 30 day challenge focused on high knees and climbers to boost your cardio, based on the popular Neila Rey workout.",
    estimatedTime: "10 min/day",
    difficulty: "Intermediate",
    images: [
      { src: "/challenges/high-knees.gif", title: "High Knees" },
      { src: "/challenges/mountain-climbers.gif", title: "Mountain Climbers" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "40 high knees, 20 climbers", duration: 10 },
      { day: 2, name: "Day 2", details: "60 high knees, 40 climbers", duration: 10 },
      { day: 3, name: "Day 3", details: "20 high knees, 60 climbers", duration: 10 },
      { day: 4, name: "Day 4", details: "40 high knees, 20 climbers", duration: 10 },
      { day: 5, name: "Day 5", details: "60 high knees, 40 climbers", duration: 10 },
      { day: 6, name: "Day 6", details: "80 high knees, 20 climbers", duration: 10 },
      { day: 7, name: "Day 7", details: "80 high knees, 40 climbers", duration: 10 },
      { day: 8, name: "Day 8", details: "40 high knees, 20 climbers", duration: 10 },
      { day: 9, name: "Day 9", details: "80 high knees, 40 climbers", duration: 10 },
      { day: 10, name: "Day 10", details: "80 high knees, 60 climbers", duration: 10 },
      { day: 11, name: "Day 11", details: "100 high knees, 20 climbers", duration: 10 },
      { day: 12, name: "Day 12", details: "80 high knees, 40 climbers", duration: 10 },
      { day: 13, name: "Day 13", details: "40 high knees, 40 climbers", duration: 10 },
      { day: 14, name: "Day 14", details: "80 high knees, 60 climbers", duration: 10 },
      { day: 15, name: "Day 15", details: "100 high knees, 60 climbers", duration: 10 },
      { day: 16, name: "Day 16", details: "140 high knees, 40 climbers", duration: 10 },
      { day: 17, name: "Day 17", details: "100 high knees, 40 climbers", duration: 10 },
      { day: 18, name: "Day 18", details: "40 high knees, 80 climbers", duration: 10 },
      { day: 19, name: "Day 19", details: "100 high knees, 40 climbers", duration: 10 },
      { day: 20, name: "Day 20", details: "140 high knees, 60 climbers", duration: 10 },
      { day: 21, name: "Day 21", details: "160 high knees, 40 climbers", duration: 10 },
      { day: 22, name: "Day 22", details: "120 high knees, 60 climbers", duration: 10 },
      { day: 23, name: "Day 23", details: "60 high knees, 20 climbers", duration: 10 },
      { day: 24, name: "Day 24", details: "100 high knees, 40 climbers", duration: 10 },
      { day: 25, name: "Day 25", details: "160 high knees, 20 climbers", duration: 10 },
      { day: 26, name: "Day 26", details: "200 high knees, 20 climbers", duration: 10 },
      { day: 27, name: "Day 27", details: "160 high knees, 40 climbers", duration: 10 },
      { day: 28, name: "Day 28", details: "100 high knees, 20 climbers", duration: 10 },
      { day: 29, name: "Day 29", details: "100 high knees, 80 climbers", duration: 10 },
      { day: 30, name: "Day 30", details: "240 high knees, 60 climbers", duration: 10 },
    ],
  },
  {
    id: 2,
    title: "Core Strength Challenge",
    duration: 30,
    description: "Build a stronger core with daily targeted exercises",
    estimatedTime: "10-15 min/day",
    difficulty: "Beginner",
    exercises: [
      {
        day: 1,
        name: "Core Foundation",
        details: "30 crunches, 20 leg raises, 30-sec plank",
        duration: 12,
      },
    ],
  },
  {
    id: 3,
    title: "Full Body Transformation",
    duration: 30,
    description: "Complete body workout combining strength and cardio",
    estimatedTime: "25-30 min/day",
    difficulty: "Advanced",
    exercises: [
      {
        day: 1,
        name: "Total Body Blast",
        details: "20 push-ups, 30 squats, 15 burpees, 45-sec plank",
        duration: 25,
      },
    ],
  },
]; 