import { Challenge } from "./types";

// Mock data for challenges
export const challenges: Challenge[] = [
  {
    id: 1,
    title: "Cardio 30 Day Challenge",
    duration: 30,
    description: "A 30 day challenge focused on high knees and climbers to boost your cardio, based on the popular Neila Rey workout.",
    estimatedTime: "10 min/day",
    difficulty: "Intermediate",
    images: [
      { src: "/challenges/high-knees.gif", title: "High Knees" },
      { src: "/challenges/mountain-climbers.gif", title: "Mountain Climbers" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "40 high knees, 20 climbers", duration: 10 },
      { day: 2, name: "Day 2", details: "60 high knees, 40 climbers", duration: 10 },
      { day: 3, name: "Day 3", details: "20 high knees, 60 climbers", duration: 10 },
      { day: 4, name: "Day 4", details: "40 high knees, 20 climbers", duration: 10 },
      { day: 5, name: "Day 5", details: "60 high knees, 40 climbers", duration: 10 },
      { day: 6, name: "Day 6", details: "80 high knees, 20 climbers", duration: 10 },
      { day: 7, name: "Day 7", details: "80 high knees, 40 climbers", duration: 10 },
      { day: 8, name: "Day 8", details: "40 high knees, 20 climbers", duration: 10 },
      { day: 9, name: "Day 9", details: "80 high knees, 40 climbers", duration: 10 },
      { day: 10, name: "Day 10", details: "80 high knees, 60 climbers", duration: 10 },
      { day: 11, name: "Day 11", details: "100 high knees, 20 climbers", duration: 10 },
      { day: 12, name: "Day 12", details: "80 high knees, 40 climbers", duration: 10 },
      { day: 13, name: "Day 13", details: "40 high knees, 40 climbers", duration: 10 },
      { day: 14, name: "Day 14", details: "80 high knees, 60 climbers", duration: 10 },
      { day: 15, name: "Day 15", details: "100 high knees, 60 climbers", duration: 10 },
      { day: 16, name: "Day 16", details: "140 high knees, 40 climbers", duration: 10 },
      { day: 17, name: "Day 17", details: "100 high knees, 40 climbers", duration: 10 },
      { day: 18, name: "Day 18", details: "40 high knees, 80 climbers", duration: 10 },
      { day: 19, name: "Day 19", details: "100 high knees, 40 climbers", duration: 10 },
      { day: 20, name: "Day 20", details: "140 high knees, 60 climbers", duration: 10 },
      { day: 21, name: "Day 21", details: "160 high knees, 40 climbers", duration: 10 },
      { day: 22, name: "Day 22", details: "120 high knees, 60 climbers", duration: 10 },
      { day: 23, name: "Day 23", details: "60 high knees, 20 climbers", duration: 10 },
      { day: 24, name: "Day 24", details: "100 high knees, 40 climbers", duration: 10 },
      { day: 25, name: "Day 25", details: "160 high knees, 20 climbers", duration: 10 },
      { day: 26, name: "Day 26", details: "200 high knees, 20 climbers", duration: 10 },
      { day: 27, name: "Day 27", details: "160 high knees, 40 climbers", duration: 10 },
      { day: 28, name: "Day 28", details: "100 high knees, 20 climbers", duration: 10 },
      { day: 29, name: "Day 29", details: "100 high knees, 80 climbers", duration: 10 },
      { day: 30, name: "Day 30", details: "240 high knees, 60 climbers", duration: 10 },
    ],
  },
  {
    id: 2,
    title: "Core Strength Challenge",
    duration: 30,
    description: "Build a stronger core with daily targeted exercises",
    estimatedTime: "10-15 min/day",
    difficulty: "Beginner",
    exercises: [
      {
        day: 1,
        name: "Core Foundation",
        details: "30 crunches, 20 leg raises, 30-sec plank",
        duration: 12,
      },
    ],
  },
  {
    id: 3,
    title: "Full Body Transformation",
    duration: 30,
    description: "Complete body workout combining strength and cardio",
    estimatedTime: "25-30 min/day",
    difficulty: "Advanced",
    exercises: [
      {
        day: 1,
        name: "Total Body Blast",
        details: "20 push-ups, 30 squats, 15 burpees, 45-sec plank",
        duration: 25,
      },
    ],
  },
  {
    id: 4,
    title: "1400 Burpees Challenge",
    duration: 30,
    description: "A 30-day challenge to complete 1400 burpees, with some plank exercises included.",
    estimatedTime: "5-15 min/day",
    difficulty: "Advanced",
    images: [
      { src: "/challenges/burpee.gif", title: "Burpee" },
      { src: "/challenges/plank.png", title: "Plank" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "10 burpees", duration: 2 },
      { day: 2, name: "Day 2", details: "20 burpees", duration: 4 },
      { day: 3, name: "Day 3", details: "25 burpees", duration: 5 },
      { day: 4, name: "Day 4", details: "30sec plank x 2", duration: 3 },
      { day: 5, name: "Day 5", details: "25 burpees", duration: 5 },
      { day: 6, name: "Day 6", details: "30 burpees", duration: 6 },
      { day: 7, name: "Day 7", details: "45 burpees", duration: 8 },
      { day: 8, name: "Day 8", details: "30sec plank x 3", duration: 4 },
      { day: 9, name: "Day 9", details: "45 burpees", duration: 8 },
      { day: 10, name: "Day 10", details: "50 burpees", duration: 9 },
      { day: 11, name: "Day 11", details: "55 burpees", duration: 10 },
      { day: 12, name: "Day 12", details: "30sec plank x 4", duration: 5 },
      { day: 13, name: "Day 13", details: "55 burpees", duration: 10 },
      { day: 14, name: "Day 14", details: "60 burpees", duration: 11 },
      { day: 15, name: "Day 15", details: "65 burpees", duration: 12 },
      { day: 16, name: "Day 16", details: "45sec plank x 2", duration: 4 },
      { day: 17, name: "Day 17", details: "65 burpees", duration: 12 },
      { day: 18, name: "Day 18", details: "70 burpees", duration: 13 },
      { day: 19, name: "Day 19", details: "75 burpees", duration: 13 },
      { day: 20, name: "Day 20", details: "45sec plank x 3", duration: 5 },
      { day: 21, name: "Day 21", details: "75 burpees", duration: 13 },
      { day: 22, name: "Day 22", details: "80 burpees", duration: 14 },
      { day: 23, name: "Day 23", details: "85 burpees", duration: 15 },
      { day: 24, name: "Day 24", details: "45sec plank x 4", duration: 6 },
      { day: 25, name: "Day 25", details: "85 burpees", duration: 15 },
      { day: 26, name: "Day 26", details: "90 burpees", duration: 16 },
      { day: 27, name: "Day 27", details: "95 burpees", duration: 17 },
      { day: 28, name: "Day 28", details: "60sec plank x 5", duration: 8 },
      { day: 29, name: "Day 29", details: "95 burpees", duration: 17 },
      { day: 30, name: "Day 30", details: "100 burpees", duration: 18 },
    ],
  },
  {
    id: 5,
    title: "50 Push-ups Challenge",
    duration: 30,
    description: "A 30-day challenge to build up to 50 consecutive push-ups, with push-up planks included for isometric strength. Up to 60 seconds rest between sets.",
    estimatedTime: "5-10 min/day",
    difficulty: "Intermediate",
    images: [
      { src: "/challenges/push-ups.png", title: "Push-up" },
      { src: "/challenges/plank.png", title: "Plank" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "2, 2, 4 push-up reps", duration: 3 },
      { day: 2, name: "Day 2", details: "3, 3, 6 push-up reps", duration: 3 },
      { day: 3, name: "Day 3", details: "3x 10sec push-up plank", duration: 3 },
      { day: 4, name: "Day 4", details: "8, 6, 4 push-up reps", duration: 4 },
      { day: 5, name: "Day 5", details: "10, 8, 6 push-up reps", duration: 4 },
      { day: 6, name: "Day 6", details: "5, 5, 2 push-up reps", duration: 3 },
      { day: 7, name: "Day 7", details: "3x 15sec push-up plank", duration: 4 },
      { day: 8, name: "Day 8", details: "6, 8, 10 push-up reps", duration: 4 },
      { day: 9, name: "Day 9", details: "8, 12, 10 push-up reps", duration: 5 },
      { day: 10, name: "Day 10", details: "4, 8, 4 push-up reps", duration: 4 },
      { day: 11, name: "Day 11", details: "3x 20sec push-up plank", duration: 4 },
      { day: 12, name: "Day 12", details: "16, 8, 6 push-up reps", duration: 5 },
      { day: 13, name: "Day 13", details: "14, 12, 14 push-up reps", duration: 5 },
      { day: 14, name: "Day 14", details: "5, 8, 5 push-up reps", duration: 4 },
      { day: 15, name: "Day 15", details: "4x 20sec push-up plank", duration: 5 },
      { day: 16, name: "Day 16", details: "5, 5, 10 push-up reps", duration: 4 },
      { day: 17, name: "Day 17", details: "20, 10, 10 push-up reps", duration: 5 },
      { day: 18, name: "Day 18", details: "8, 15, 8 push-up reps", duration: 5 },
      { day: 19, name: "Day 19", details: "5x 20sec push-up plank", duration: 5 },
      { day: 20, name: "Day 20", details: "10, 20, 10 push-up reps", duration: 5 },
      { day: 21, name: "Day 21", details: "10, 14, 18 push-up reps", duration: 5 },
      { day: 22, name: "Day 22", details: "20, 5, 5 push-up reps", duration: 5 },
      { day: 23, name: "Day 23", details: "5x 25sec push-up plank", duration: 6 },
      { day: 24, name: "Day 24", details: "5, 10, 5 push-up reps", duration: 4 },
      { day: 25, name: "Day 25", details: "5, 15, 10 push-up reps", duration: 5 },
      { day: 26, name: "Day 26", details: "25, 15, 15 push-up reps", duration: 6 },
      { day: 27, name: "Day 27", details: "6x 25sec push-up plank", duration: 6 },
      { day: 28, name: "Day 28", details: "30, 5, 5 push-up reps", duration: 6 },
      { day: 29, name: "Day 29", details: "Rest Day", duration: 0 },
      { day: 30, name: "Day 30", details: "50 push-ups in one go", duration: 5 },
    ],
  },
  {
    id: 6,
    title: "Legs of Steel Challenge",
    duration: 30,
    description: "A 30-day challenge to build strong and powerful legs with lunges and side lunges. Each workout consists of 3 sets with 20 seconds rest between sets.",
    estimatedTime: "5-10 min/day",
    difficulty: "Intermediate",
    images: [
      { src: "/challenges/lunges.png", title: "Lunge" },
      { src: "/challenges/side-lunges.png", title: "Side Lunge" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "22 lunges, 3 sets, 20s rest", duration: 4 },
      { day: 2, name: "Day 2", details: "12 side lunges, 3 sets, 20s rest", duration: 3 },
      { day: 3, name: "Day 3", details: "22 lunges, 3 sets, 20s rest", duration: 4 },
      { day: 4, name: "Day 4", details: "12 side lunges, 3 sets, 20s rest", duration: 3 },
      { day: 5, name: "Day 5", details: "22 lunges, 3 sets, 20s rest", duration: 4 },
      { day: 6, name: "Day 6", details: "12 side lunges, 3 sets, 20s rest", duration: 3 },
      { day: 7, name: "Day 7", details: "24 lunges, 3 sets, 20s rest", duration: 5 },
      { day: 8, name: "Day 8", details: "14 side lunges, 3 sets, 20s rest", duration: 4 },
      { day: 9, name: "Day 9", details: "24 lunges, 3 sets, 20s rest", duration: 5 },
      { day: 10, name: "Day 10", details: "14 side lunges, 3 sets, 20s rest", duration: 4 },
      { day: 11, name: "Day 11", details: "24 lunges, 3 sets, 20s rest", duration: 5 },
      { day: 12, name: "Day 12", details: "14 side lunges, 3 sets, 20s rest", duration: 4 },
      { day: 13, name: "Day 13", details: "26 lunges, 3 sets, 20s rest", duration: 5 },
      { day: 14, name: "Day 14", details: "16 side lunges, 3 sets, 20s rest", duration: 4 },
      { day: 15, name: "Day 15", details: "26 lunges, 3 sets, 20s rest", duration: 5 },
      { day: 16, name: "Day 16", details: "16 side lunges, 3 sets, 20s rest", duration: 4 },
      { day: 17, name: "Day 17", details: "26 lunges, 3 sets, 20s rest", duration: 5 },
      { day: 18, name: "Day 18", details: "16 side lunges, 3 sets, 20s rest", duration: 4 },
      { day: 19, name: "Day 19", details: "28 lunges, 3 sets, 20s rest", duration: 6 },
      { day: 20, name: "Day 20", details: "18 side lunges, 3 sets, 20s rest", duration: 5 },
      { day: 21, name: "Day 21", details: "28 lunges, 3 sets, 20s rest", duration: 6 },
      { day: 22, name: "Day 22", details: "18 side lunges, 3 sets, 20s rest", duration: 5 },
      { day: 23, name: "Day 23", details: "28 lunges, 3 sets, 20s rest", duration: 6 },
      { day: 24, name: "Day 24", details: "18 side lunges, 3 sets, 20s rest", duration: 5 },
      { day: 25, name: "Day 25", details: "30 lunges, 3 sets, 20s rest", duration: 6 },
      { day: 26, name: "Day 26", details: "20 side lunges, 3 sets, 20s rest", duration: 5 },
      { day: 27, name: "Day 27", details: "30 lunges, 3 sets, 20s rest", duration: 6 },
      { day: 28, name: "Day 28", details: "20 side lunges, 3 sets, 20s rest", duration: 5 },
      { day: 29, name: "Day 29", details: "30 lunges, 3 sets, 20s rest", duration: 6 },
      { day: 30, name: "Day 30", details: "20 side lunges, 3 sets, 20s rest", duration: 5 },
    ],
  },
  {
    id: 7,
    title: "Calves of Steel Challenge",
    duration: 30,
    description: "A 30-day challenge for stronger, more defined calves. This challenge alternates between high-repetition calf raises and isometric holds to build endurance and strength. Calf raises can be done throughout the day.",
    estimatedTime: "5-10 min/day",
    difficulty: "Beginner",
    images: [
      { src: "/challenges/calf-raises.png", title: "Calf Raise" },
    ],
    exercises: [
        { day: 1, name: "Day 1", details: "60 calf raises in total throughout the day", duration: 3 },
        { day: 2, name: "Day 2", details: "20 seconds calf raise hold, 2 sets, 30sec rest", duration: 2 },
        { day: 3, name: "Day 3", details: "70 calf raises in total throughout the day", duration: 3 },
        { day: 4, name: "Day 4", details: "20 seconds calf raise hold, 2 sets, 30sec rest", duration: 2 },
        { day: 5, name: "Day 5", details: "80 calf raises in total throughout the day", duration: 4 },
        { day: 6, name: "Day 6", details: "30 seconds calf raise hold, 2 sets, 30sec rest", duration: 2 },
        { day: 7, name: "Day 7", details: "90 calf raises in total throughout the day", duration: 4 },
        { day: 8, name: "Day 8", details: "30 seconds calf raise hold, 2 sets, 30sec rest", duration: 2 },
        { day: 9, name: "Day 9", details: "100 calf raises in total throughout the day", duration: 5 },
        { day: 10, name: "Day 10", details: "40 seconds calf raise hold, 2 sets, 30sec rest", duration: 2 },
        { day: 11, name: "Day 11", details: "110 calf raises in total throughout the day", duration: 5 },
        { day: 12, name: "Day 12", details: "40 seconds calf raise hold, 2 sets, 30sec rest", duration: 2 },
        { day: 13, name: "Day 13", details: "120 calf raises in total throughout the day", duration: 6 },
        { day: 14, name: "Day 14", details: "50 seconds calf raise hold, 2 sets, 30sec rest", duration: 3 },
        { day: 15, name: "Day 15", details: "130 calf raises in total throughout the day", duration: 6 },
        { day: 16, name: "Day 16", details: "50 seconds calf raise hold, 2 sets, 30sec rest", duration: 3 },
        { day: 17, name: "Day 17", details: "140 calf raises in total throughout the day", duration: 7 },
        { day: 18, name: "Day 18", details: "60 seconds calf raise hold, 2 sets, 30sec rest", duration: 3 },
        { day: 19, name: "Day 19", details: "150 calf raises in total throughout the day", duration: 7 },
        { day: 20, name: "Day 20", details: "60 seconds calf raise hold, 2 sets, 30sec rest", duration: 3 },
        { day: 21, name: "Day 21", details: "160 calf raises in total throughout the day", duration: 8 },
        { day: 22, name: "Day 22", details: "1min 10sec calf raise hold, 2 sets, 30sec rest", duration: 3 },
        { day: 23, name: "Day 23", details: "170 calf raises in total throughout the day", duration: 8 },
        { day: 24, name: "Day 24", details: "1min 10sec calf raise hold, 2 sets, 30sec rest", duration: 3 },
        { day: 25, name: "Day 25", details: "180 calf raises in total throughout the day", duration: 9 },
        { day: 26, name: "Day 26", details: "1min 20sec calf raise hold, 2 sets, 30sec rest", duration: 4 },
        { day: 27, name: "Day 27", details: "190 calf raises in total throughout the day", duration: 9 },
        { day: 28, name: "Day 28", details: "1min 20sec calf raise hold, 2 sets, 30sec rest", duration: 4 },
        { day: 29, name: "Day 29", details: "200 calf raises in total throughout the day", duration: 10 },
        { day: 30, name: "Day 30", details: "1min 30sec calf raise hold, 2 sets, 30sec rest", duration: 4 },
    ],
  },
  {
    id: 9,
    title: "Hollow Hold Challenge",
    duration: 30,
    description: "A 30-day challenge to master the hollow hold and superman hold, building a rock-solid core by alternating between two foundational gymnastic exercises.",
    estimatedTime: "< 5 min/day",
    difficulty: "Intermediate",
    images: [
      { src: "/challenges/hollow-hold.png", title: "Hollow Hold" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "20 seconds hollow hold", duration: 1 },
      { day: 2, name: "Day 2", details: "20 seconds superman hold", duration: 1 },
      { day: 3, name: "Day 3", details: "25 seconds hollow hold", duration: 1 },
      { day: 4, name: "Day 4", details: "25 seconds superman hold", duration: 1 },
      { day: 5, name: "Day 5", details: "30 seconds hollow hold", duration: 1 },
      { day: 6, name: "Day 6", details: "30 seconds superman hold", duration: 1 },
      { day: 7, name: "Day 7", details: "35 seconds hollow hold", duration: 1 },
      { day: 8, name: "Day 8", details: "35 seconds superman hold", duration: 1 },
      { day: 9, name: "Day 9", details: "40 seconds hollow hold", duration: 1 },
      { day: 10, name: "Day 10", details: "40 seconds superman hold", duration: 1 },
      { day: 11, name: "Day 11", details: "45 seconds hollow hold", duration: 1 },
      { day: 12, name: "Day 12", details: "45 seconds superman hold", duration: 1 },
      { day: 13, name: "Day 13", details: "50 seconds hollow hold", duration: 1 },
      { day: 14, name: "Day 14", details: "50 seconds superman hold", duration: 1 },
      { day: 15, name: "Day 15", details: "55 seconds hollow hold", duration: 1 },
      { day: 16, name: "Day 16", details: "55 seconds superman hold", duration: 1 },
      { day: 17, name: "Day 17", details: "60 seconds hollow hold", duration: 1 },
      { day: 18, name: "Day 18", details: "60 seconds superman hold", duration: 1 },
      { day: 19, name: "Day 19", details: "1min 10sec hollow hold", duration: 2 },
      { day: 20, name: "Day 20", details: "1min 10sec superman hold", duration: 2 },
      { day: 21, name: "Day 21", details: "1min 20sec hollow hold", duration: 2 },
      { day: 22, name: "Day 22", details: "1min 20sec superman hold", duration: 2 },
      { day: 23, name: "Day 23", details: "1min 30sec hollow hold", duration: 2 },
      { day: 24, name: "Day 24", details: "1min 30sec superman hold", duration: 2 },
      { day: 25, name: "Day 25", details: "1min 40sec hollow hold", duration: 2 },
      { day: 26, name: "Day 26", details: "1min 40sec superman hold", duration: 2 },
      { day: 27, name: "Day 27", details: "1min 50sec hollow hold", duration: 2 },
      { day: 28, name: "Day 28", details: "1min 50sec superman hold", duration: 2 },
      { day: 29, name: "Day 29", details: "2 minutes hollow hold", duration: 2 },
      { day: 30, name: "Day 30", details: "2 minutes superman hold", duration: 2 },
    ],
  },
  {
    id: 10,
    title: "The Long Run",
    duration: 30,
    description: "A 30-day challenge to build running endurance, progressing from 4 to 40 minutes. The plan includes a mix of running, walking, and sprinting to improve cardiovascular fitness.",
    estimatedTime: "4-40 min/day",
    difficulty: "Varies",
    exercises: [
      { day: 1, name: "Day 1", details: "4min run, 1min rest, repeat 2 times", duration: 10 },
      { day: 2, name: "Day 2", details: "5min run, 5min walk", duration: 10 },
      { day: 3, name: "Day 3", details: "5 x 10sec sprints", duration: 5 },
      { day: 4, name: "Day 4", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 5, name: "Day 5", details: "10min run", duration: 10 },
      { day: 6, name: "Day 6", details: "5min run, 5min walk", duration: 10 },
      { day: 7, name: "Day 7", details: "5 x 10sec sprints", duration: 5 },
      { day: 8, name: "Day 8", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 9, name: "Day 9", details: "15min run", duration: 15 },
      { day: 10, name: "Day 10", details: "5min run, 5min walk", duration: 10 },
      { day: 11, name: "Day 11", details: "5 x 10sec sprints", duration: 5 },
      { day: 12, name: "Day 12", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 13, name: "Day 13", details: "20min run", duration: 20 },
      { day: 14, name: "Day 14", details: "10min run, 10min walk", duration: 20 },
      { day: 15, name: "Day 15", details: "5 x 10sec sprints", duration: 5 },
      { day: 16, name: "Day 16", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 17, name: "Day 17", details: "25min run", duration: 25 },
      { day: 18, name: "Day 18", details: "10min run, 10min walk", duration: 20 },
      { day: 19, name: "Day 19", details: "5 x 10sec sprints", duration: 5 },
      { day: 20, name: "Day 20", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 21, name: "Day 21", details: "30min run", duration: 30 },
      { day: 22, name: "Day 22", details: "10min run, 10min walk", duration: 20 },
      { day: 23, name: "Day 23", details: "5 x 10sec sprints", duration: 5 },
      { day: 24, name: "Day 24", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 25, name: "Day 25", details: "35min run", duration: 35 },
      { day: 26, name: "Day 26", details: "15min run, 15min walk", duration: 30 },
      { day: 27, name: "Day 27", details: "5 x 10sec sprints", duration: 5 },
      { day: 28, name: "Day 28", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 29, name: "Day 29", details: "15min run, 15min walk", duration: 30 },
      { day: 30, name: "Day 30", details: "40min run", duration: 40 },
    ],
  },
  {
    id: 11,
    title: "Jump Rope 30-Day Challenge",
    duration: 30,
    description: "A 30-day challenge to improve cardio and coordination with a variety of jump rope workouts, including timed sets, non-stop skips, and total skips per day.",
    estimatedTime: "5-15 min/day",
    difficulty: "Intermediate",
    images: [
      { src: "/challenges/jump-rope.png", title: "Jump Rope" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "1 min skips, 1 min rest, 3 sets in total", duration: 6 },
      { day: 2, name: "Day 2", details: "4 min in total throughout the day", duration: 4 },
      { day: 3, name: "Day 3", details: "2 min skips non-stop", duration: 2 },
      { day: 4, name: "Day 4", details: "1 min skips, 1 min rest, 3 sets in total", duration: 6 },
      { day: 5, name: "Day 5", details: "200 skips one workout", duration: 4 },
      { day: 6, name: "Day 6", details: "1 min skips, 1 min rest, 3 sets in total", duration: 6 },
      { day: 7, name: "Day 7", details: "4 min in total throughout the day", duration: 4 },
      { day: 8, name: "Day 8", details: "2 min skips non-stop", duration: 2 },
      { day: 9, name: "Day 9", details: "1 min skips, 1 min rest, 3 sets in total", duration: 6 },
      { day: 10, name: "Day 10", details: "400 skips one workout", duration: 8 },
      { day: 11, name: "Day 11", details: "1 min skips, 1 min rest, 4 sets in total", duration: 8 },
      { day: 12, name: "Day 12", details: "6 min in total throughout the day", duration: 6 },
      { day: 13, name: "Day 13", details: "3 min skips non-stop", duration: 3 },
      { day: 14, name: "Day 14", details: "1 min skips, 1 min rest, 4 sets in total", duration: 8 },
      { day: 15, name: "Day 15", details: "450 skips one workout", duration: 9 },
      { day: 16, name: "Day 16", details: "1 min skips, 1 min rest, 4 sets in total", duration: 8 },
      { day: 17, name: "Day 17", details: "6 min in total throughout the day", duration: 6 },
      { day: 18, name: "Day 18", details: "3 min skips non-stop", duration: 3 },
      { day: 19, name: "Day 19", details: "1 min skips, 1 min rest, 4 sets in total", duration: 8 },
      { day: 20, name: "Day 20", details: "600 skips one workout", duration: 12 },
      { day: 21, name: "Day 21", details: "1 min skips, 1 min rest, 4 sets in total", duration: 8 },
      { day: 22, name: "Day 22", details: "8 min in total throughout the day", duration: 8 },
      { day: 23, name: "Day 23", details: "4 min skips non-stop", duration: 4 },
      { day: 24, name: "Day 24", details: "1 min skips, 1 min rest, 4 sets in total", duration: 8 },
      { day: 25, name: "Day 25", details: "800 skips one workout", duration: 16 },
      { day: 26, name: "Day 26", details: "1 min skips, 1 min rest, 5 sets in total", duration: 10 },
      { day: 27, name: "Day 27", details: "10 min in total throughout the day", duration: 10 },
      { day: 28, name: "Day 28", details: "4 min skips non-stop", duration: 4 },
      { day: 29, name: "Day 29", details: "1 min skips, 1 min rest, 5 sets in total", duration: 10 },
      { day: 30, name: "Day 30", details: "1000 skips one workout", duration: 20 },
    ],
  },
];

// Helper function to get challenge by ID
export function getChallengeById(id: number): Challenge | undefined {
  return challenges.find(challenge => challenge.id === id);
}

// Helper function to get all challenges
export function getAllChallenges(): Challenge[] {
  return challenges;
}