import { challengeAsset } from "./challenge-assets";
import { Challenge } from "./types";

// Mock data for challenges
export const challenges: Challenge[] = [
  {
    id: "550e8400-e29b-41d4-a716-446655440001",
    title: "Cardio 30 Day Challenge",
    duration: 30,
    description: "A 30 day challenge focused on high knees and climbers to boost your cardio, based on the popular Neila Rey workout.",
    estimatedTime: "10 min/day",
    difficulty: "Intermediate",
    images: [
      { src: challengeAsset("high-knees.gif"), title: "High knees / cardio" },
      { src: challengeAsset("mountain-climbers.gif"), title: "Mountain climbers" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "40 high knees, 20 climbers", duration: 10 },
      { day: 2, name: "Day 2", details: "60 high knees, 40 climbers", duration: 10 },
      { day: 3, name: "Day 3", details: "20 high knees, 60 climbers", duration: 10 },
      { day: 4, name: "Day 4", details: "40 high knees, 20 climbers", duration: 10 },
      { day: 5, name: "Day 5", details: "60 high knees, 40 climbers", duration: 10 },
      { day: 6, name: "Day 6", details: "80 high knees, 20 climbers", duration: 10 },
      { day: 7, name: "Day 7", details: "80 high knees, 40 climbers", duration: 10 },
      { day: 8, name: "Day 8", details: "40 high knees, 20 climbers", duration: 10 },
      { day: 9, name: "Day 9", details: "80 high knees, 40 climbers", duration: 10 },
      { day: 10, name: "Day 10", details: "80 high knees, 60 climbers", duration: 10 },
      { day: 11, name: "Day 11", details: "100 high knees, 20 climbers", duration: 10 },
      { day: 12, name: "Day 12", details: "80 high knees, 40 climbers", duration: 10 },
      { day: 13, name: "Day 13", details: "40 high knees, 40 climbers", duration: 10 },
      { day: 14, name: "Day 14", details: "80 high knees, 60 climbers", duration: 10 },
      { day: 15, name: "Day 15", details: "100 high knees, 60 climbers", duration: 10 },
      { day: 16, name: "Day 16", details: "140 high knees, 40 climbers", duration: 10 },
      { day: 17, name: "Day 17", details: "100 high knees, 40 climbers", duration: 10 },
      { day: 18, name: "Day 18", details: "40 high knees, 80 climbers", duration: 10 },
      { day: 19, name: "Day 19", details: "100 high knees, 40 climbers", duration: 10 },
      { day: 20, name: "Day 20", details: "140 high knees, 60 climbers", duration: 10 },
      { day: 21, name: "Day 21", details: "160 high knees, 40 climbers", duration: 10 },
      { day: 22, name: "Day 22", details: "120 high knees, 60 climbers", duration: 10 },
      { day: 23, name: "Day 23", details: "60 high knees, 20 climbers", duration: 10 },
      { day: 24, name: "Day 24", details: "100 high knees, 40 climbers", duration: 10 },
      { day: 25, name: "Day 25", details: "160 high knees, 20 climbers", duration: 10 },
      { day: 26, name: "Day 26", details: "200 high knees, 20 climbers", duration: 10 },
      { day: 27, name: "Day 27", details: "160 high knees, 40 climbers", duration: 10 },
      { day: 28, name: "Day 28", details: "100 high knees, 20 climbers", duration: 10 },
      { day: 29, name: "Day 29", details: "100 high knees, 80 climbers", duration: 10 },
      { day: 30, name: "Day 30", details: "240 high knees, 60 climbers", duration: 10 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440002",
    title: "Core Strength Challenge",
    duration: 30,
    description: "Build a stronger core with daily targeted exercises",
    estimatedTime: "12-41 min/day",
    difficulty: "Beginner",
    images: [
      { src: challengeAsset("ab-crunches.png"), title: "Crunches" },
      { src: challengeAsset("ab-leg-raises.png"), title: "Leg raises" },
      { src: challengeAsset("plank.png"), title: "Plank" },
    ],
    exercises: [
      {
        day: 1,
        name: "Core Foundation",
        details: "30 crunches, 20 leg raises, 30-sec plank",
        duration: 12,
      },
      {
        day: 2,
        name: "Core Foundation",
        details: "35 crunches, 25 leg raises, 35-sec plank",
        duration: 13,
      },
      {
        day: 3,
        name: "Core Foundation",
        details: "40 crunches, 30 leg raises, 40-sec plank",
        duration: 14,
      },
      {
        day: 4,
        name: "Core Foundation",
        details: "45 crunches, 35 leg raises, 45-sec plank",
        duration: 15,
      },
      {
        day: 5,
        name: "Core Foundation",
        details: "50 crunches, 40 leg raises, 50-sec plank",
        duration: 16,
      },
      {
        day: 6,
        name: "Core Foundation",
        details: "55 crunches, 45 leg raises, 55-sec plank",
        duration: 17,
      },
      {
        day: 7,
        name: "Core Foundation",
        details: "60 crunches, 50 leg raises, 60-sec plank",
        duration: 18,
      },
      {
        day: 8,
        name: "Core Foundation",
        details: "65 crunches, 55 leg raises, 65-sec plank",
        duration: 19,
      },
      {
        day: 9,
        name: "Core Foundation",
        details: "70 crunches, 60 leg raises, 70-sec plank",
        duration: 20,
      },
      {
        day: 10,
        name: "Core Foundation",
        details: "75 crunches, 65 leg raises, 75-sec plank",
        duration: 21,
      },
      {
        day: 11,
        name: "Core Foundation",
        details: "80 crunches, 70 leg raises, 80-sec plank",
        duration: 22,
      },
      {
        day: 12,
        name: "Core Foundation",
        details: "85 crunches, 75 leg raises, 85-sec plank",
        duration: 23,
      },
      {
        day: 13,
        name: "Core Foundation",
        details: "90 crunches, 80 leg raises, 90-sec plank",
        duration: 24,
      },
      {
        day: 14,
        name: "Core Foundation",
        details: "95 crunches, 85 leg raises, 95-sec plank",
        duration: 25,
      },
      {
        day: 15,
        name: "Core Foundation",
        details: "100 crunches, 90 leg raises, 100-sec plank",
        duration: 26,
      },
      {
        day: 16,
        name: "Core Foundation",
        details: "105 crunches, 95 leg raises, 105-sec plank",
        duration: 27,
      },
      {
        day: 17,
        name: "Core Foundation",
        details: "110 crunches, 100 leg raises, 110-sec plank",
        duration: 28,
      },
      {
        day: 18,
        name: "Core Foundation",
        details: "115 crunches, 105 leg raises, 115-sec plank",
        duration: 29,
      },
      {
        day: 19,
        name: "Core Foundation",
        details: "120 crunches, 110 leg raises, 120-sec plank",
        duration: 30,
      },
      {
        day: 20,
        name: "Core Foundation",
        details: "125 crunches, 115 leg raises, 125-sec plank",
        duration: 31,
      },
      {
        day: 21,
        name: "Core Foundation",
        details: "130 crunches, 120 leg raises, 130-sec plank",
        duration: 32,
      },
      {
        day: 22,
        name: "Core Foundation",
        details: "135 crunches, 125 leg raises, 135-sec plank",
        duration: 33,
      },
      {
        day: 23,
        name: "Core Foundation",
        details: "140 crunches, 130 leg raises, 140-sec plank",
        duration: 34,
      },
      {
        day: 24,
        name: "Core Foundation",
        details: "145 crunches, 135 leg raises, 145-sec plank",
        duration: 35,
      },
      {
        day: 25,
        name: "Core Foundation",
        details: "150 crunches, 140 leg raises, 150-sec plank",
        duration: 36,
      },
      {
        day: 26,
        name: "Core Foundation",
        details: "155 crunches, 145 leg raises, 155-sec plank",
        duration: 37,
      },
      {
        day: 27,
        name: "Core Foundation",
        details: "160 crunches, 150 leg raises, 160-sec plank",
        duration: 38,
      },
      {
        day: 28,
        name: "Core Foundation",
        details: "165 crunches, 155 leg raises, 165-sec plank",
        duration: 39,
      },
      {
        day: 29,
        name: "Core Foundation",
        details: "170 crunches, 160 leg raises, 170-sec plank",
        duration: 40,
      },
      {
        day: 30,
        name: "Core Foundation",
        details: "175 crunches, 165 leg raises, 175-sec plank",
        duration: 41,
      },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440003",
    title: "Full Body Transformation",
    duration: 30,
    description: "Complete body workout combining strength and cardio",
    estimatedTime: "25-54 min/day",
    difficulty: "Advanced",
    images: [
      { src: challengeAsset("push-ups.png"), title: "Push-up" },
      { src: challengeAsset("squats.png"), title: "Squats" },
      { src: challengeAsset("burpees-50-one-go.png"), title: "Burpee" },
      { src: challengeAsset("plank.png"), title: "Plank" },
    ],
    exercises: [
      {
        day: 1,
        name: "Total Body Blast",
        details: "20 push-ups, 30 squats, 15 burpees, 45-sec plank",
        duration: 25,
      },
      {
        day: 2,
        name: "Total Body Blast",
        details: "25 push-ups, 35 squats, 20 burpees, 50-sec plank",
        duration: 26,
      },
      {
        day: 3,
        name: "Total Body Blast",
        details: "30 push-ups, 40 squats, 25 burpees, 55-sec plank",
        duration: 27,
      },
      {
        day: 4,
        name: "Total Body Blast",
        details: "35 push-ups, 45 squats, 30 burpees, 60-sec plank",
        duration: 28,
      },
      {
        day: 5,
        name: "Total Body Blast",
        details: "40 push-ups, 50 squats, 35 burpees, 65-sec plank",
        duration: 29,
      },
      {
        day: 6,
        name: "Total Body Blast",
        details: "45 push-ups, 55 squats, 40 burpees, 70-sec plank",
        duration: 30,
      },
      {
        day: 7,
        name: "Total Body Blast",
        details: "50 push-ups, 60 squats, 45 burpees, 75-sec plank",
        duration: 31,
      },
      {
        day: 8,
        name: "Total Body Blast",
        details: "55 push-ups, 65 squats, 50 burpees, 80-sec plank",
        duration: 32,
      },
      {
        day: 9,
        name: "Total Body Blast",
        details: "60 push-ups, 70 squats, 55 burpees, 85-sec plank",
        duration: 33,
      },
      {
        day: 10,
        name: "Total Body Blast",
        details: "65 push-ups, 75 squats, 60 burpees, 90-sec plank",
        duration: 34,
      },
      {
        day: 11,
        name: "Total Body Blast",
        details: "70 push-ups, 80 squats, 65 burpees, 95-sec plank",
        duration: 35,
      },
      {
        day: 12,
        name: "Total Body Blast",
        details: "75 push-ups, 85 squats, 70 burpees, 100-sec plank",
        duration: 36,
      },
      {
        day: 13,
        name: "Total Body Blast",
        details: "80 push-ups, 90 squats, 75 burpees, 105-sec plank",
        duration: 37,
      },
      {
        day: 14,
        name: "Total Body Blast",
        details: "85 push-ups, 95 squats, 80 burpees, 110-sec plank",
        duration: 38,
      },
      {
        day: 15,
        name: "Total Body Blast",
        details: "90 push-ups, 100 squats, 85 burpees, 115-sec plank",
        duration: 39,
      },
      {
        day: 16,
        name: "Total Body Blast",
        details: "95 push-ups, 105 squats, 90 burpees, 120-sec plank",
        duration: 40,
      },
      {
        day: 17,
        name: "Total Body Blast",
        details: "100 push-ups, 110 squats, 95 burpees, 125-sec plank",
        duration: 41,
      },
      {
        day: 18,
        name: "Total Body Blast",
        details: "105 push-ups, 115 squats, 100 burpees, 130-sec plank",
        duration: 42,
      },
      {
        day: 19,
        name: "Total Body Blast",
        details: "110 push-ups, 120 squats, 105 burpees, 135-sec plank",
        duration: 43,
      },
      {
        day: 20,
        name: "Total Body Blast",
        details: "115 push-ups, 125 squats, 110 burpees, 140-sec plank",
        duration: 44,
      },
      {
        day: 21,
        name: "Total Body Blast",
        details: "120 push-ups, 130 squats, 115 burpees, 145-sec plank",
        duration: 45,
      },
      {
        day: 22,
        name: "Total Body Blast",
        details: "125 push-ups, 135 squats, 120 burpees, 150-sec plank",
        duration: 46,
      },
      {
        day: 23,
        name: "Total Body Blast",
        details: "130 push-ups, 140 squats, 125 burpees, 155-sec plank",
        duration: 47,
      },
      {
        day: 24,
        name: "Total Body Blast",
        details: "135 push-ups, 145 squats, 130 burpees, 160-sec plank",
        duration: 48,
      },
      {
        day: 25,
        name: "Total Body Blast",
        details: "140 push-ups, 150 squats, 135 burpees, 165-sec plank",
        duration: 49,
      },
      {
        day: 26,
        name: "Total Body Blast",
        details: "145 push-ups, 155 squats, 140 burpees, 170-sec plank",
        duration: 50,
      },
      {
        day: 27,
        name: "Total Body Blast",
        details: "150 push-ups, 160 squats, 145 burpees, 175-sec plank",
        duration: 51,
      },
      {
        day: 28,
        name: "Total Body Blast",
        details: "155 push-ups, 165 squats, 150 burpees, 180-sec plank",
        duration: 52,
      },
      {
        day: 29,
        name: "Total Body Blast",
        details: "160 push-ups, 170 squats, 155 burpees, 185-sec plank",
        duration: 53,
      },
      {
        day: 30,
        name: "Total Body Blast",
        details: "165 push-ups, 175 squats, 160 burpees, 190-sec plank",
        duration: 54,
      },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440004",
    title: "1400 Burpees Challenge",
    duration: 30,
    description: "A 30-day challenge to complete 1400 burpees, with some plank exercises included.",
    estimatedTime: "5-15 min/day",
    difficulty: "Advanced",
    images: [
      { src: challengeAsset("burpees-50-one-go.png"), title: "Burpee" },
      { src: challengeAsset("plank.png"), title: "Plank" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "10 burpees", duration: 2 },
      { day: 2, name: "Day 2", details: "20 burpees", duration: 4 },
      { day: 3, name: "Day 3", details: "25 burpees", duration: 5 },
      { day: 4, name: "Day 4", details: "30sec plank x 2", duration: 3 },
      { day: 5, name: "Day 5", details: "25 burpees", duration: 5 },
      { day: 6, name: "Day 6", details: "30 burpees", duration: 6 },
      { day: 7, name: "Day 7", details: "45 burpees", duration: 8 },
      { day: 8, name: "Day 8", details: "30sec plank x 3", duration: 4 },
      { day: 9, name: "Day 9", details: "45 burpees", duration: 8 },
      { day: 10, name: "Day 10", details: "50 burpees", duration: 9 },
      { day: 11, name: "Day 11", details: "55 burpees", duration: 10 },
      { day: 12, name: "Day 12", details: "30sec plank x 4", duration: 5 },
      { day: 13, name: "Day 13", details: "55 burpees", duration: 10 },
      { day: 14, name: "Day 14", details: "60 burpees", duration: 11 },
      { day: 15, name: "Day 15", details: "65 burpees", duration: 12 },
      { day: 16, name: "Day 16", details: "45sec plank x 2", duration: 4 },
      { day: 17, name: "Day 17", details: "65 burpees", duration: 12 },
      { day: 18, name: "Day 18", details: "70 burpees", duration: 13 },
      { day: 19, name: "Day 19", details: "75 burpees", duration: 13 },
      { day: 20, name: "Day 20", details: "45sec plank x 3", duration: 5 },
      { day: 21, name: "Day 21", details: "75 burpees", duration: 13 },
      { day: 22, name: "Day 22", details: "80 burpees", duration: 14 },
      { day: 23, name: "Day 23", details: "85 burpees", duration: 15 },
      { day: 24, name: "Day 24", details: "45sec plank x 4", duration: 6 },
      { day: 25, name: "Day 25", details: "85 burpees", duration: 15 },
      { day: 26, name: "Day 26", details: "90 burpees", duration: 16 },
      { day: 27, name: "Day 27", details: "95 burpees", duration: 17 },
      { day: 28, name: "Day 28", details: "60sec plank x 5", duration: 8 },
      { day: 29, name: "Day 29", details: "95 burpees", duration: 17 },
      { day: 30, name: "Day 30", details: "100 burpees", duration: 18 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440005",
    title: "50 Push-ups Challenge",
    duration: 30,
    description: "A 30-day challenge to build up to 50 consecutive push-ups, with push-up planks included for isometric strength. Up to 60 seconds rest between sets.",
    estimatedTime: "5-10 min/day",
    difficulty: "Intermediate",
    images: [
      { src: challengeAsset("push-ups.png"), title: "Push-up" },
      { src: challengeAsset("plank.png"), title: "Plank" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "2, 2, 4 push-up reps", duration: 3 },
      { day: 2, name: "Day 2", details: "3, 3, 6 push-up reps", duration: 3 },
      { day: 3, name: "Day 3", details: "3x 10sec push-up plank", duration: 3 },
      { day: 4, name: "Day 4", details: "8, 6, 4 push-up reps", duration: 4 },
      { day: 5, name: "Day 5", details: "10, 8, 6 push-up reps", duration: 4 },
      { day: 6, name: "Day 6", details: "5, 5, 2 push-up reps", duration: 3 },
      { day: 7, name: "Day 7", details: "3x 15sec push-up plank", duration: 4 },
      { day: 8, name: "Day 8", details: "6, 8, 10 push-up reps", duration: 4 },
      { day: 9, name: "Day 9", details: "8, 12, 10 push-up reps", duration: 5 },
      { day: 10, name: "Day 10", details: "4, 8, 4 push-up reps", duration: 4 },
      { day: 11, name: "Day 11", details: "3x 20sec push-up plank", duration: 4 },
      { day: 12, name: "Day 12", details: "16, 8, 6 push-up reps", duration: 5 },
      { day: 13, name: "Day 13", details: "14, 12, 14 push-up reps", duration: 5 },
      { day: 14, name: "Day 14", details: "5, 8, 5 push-up reps", duration: 4 },
      { day: 15, name: "Day 15", details: "4x 20sec push-up plank", duration: 5 },
      { day: 16, name: "Day 16", details: "5, 5, 10 push-up reps", duration: 4 },
      { day: 17, name: "Day 17", details: "20, 10, 10 push-up reps", duration: 5 },
      { day: 18, name: "Day 18", details: "8, 15, 8 push-up reps", duration: 5 },
      { day: 19, name: "Day 19", details: "5x 20sec push-up plank", duration: 5 },
      { day: 20, name: "Day 20", details: "10, 20, 10 push-up reps", duration: 5 },
      { day: 21, name: "Day 21", details: "10, 14, 18 push-up reps", duration: 5 },
      { day: 22, name: "Day 22", details: "20, 5, 5 push-up reps", duration: 5 },
      { day: 23, name: "Day 23", details: "5x 25sec push-up plank", duration: 6 },
      { day: 24, name: "Day 24", details: "5, 10, 5 push-up reps", duration: 4 },
      { day: 25, name: "Day 25", details: "5, 15, 10 push-up reps", duration: 5 },
      { day: 26, name: "Day 26", details: "25, 15, 15 push-up reps", duration: 6 },
      { day: 27, name: "Day 27", details: "6x 25sec push-up plank", duration: 6 },
      { day: 28, name: "Day 28", details: "30, 5, 5 push-up reps", duration: 6 },
      { day: 29, name: "Day 29", details: "Rest Day", duration: 0 },
      { day: 30, name: "Day 30", details: "50 push-ups in one go", duration: 5 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440006",
    title: "Legs of Steel Challenge",
    duration: 30,
    description: "A 30-day challenge to build strong and powerful legs with lunges and side lunges. Each workout consists of 3 sets with 20 seconds rest between sets.",
    estimatedTime: "5-10 min/day",
    difficulty: "Intermediate",
    images: [
      { src: challengeAsset("lunges.png"), title: "Lunge" },
      { src: challengeAsset("side-lunges.png"), title: "Side Lunge" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "22 lunges, 3 sets, 20s rest", duration: 4 },
      { day: 2, name: "Day 2", details: "12 side lunges, 3 sets, 20s rest", duration: 3 },
      { day: 3, name: "Day 3", details: "22 lunges, 3 sets, 20s rest", duration: 4 },
      { day: 4, name: "Day 4", details: "12 side lunges, 3 sets, 20s rest", duration: 3 },
      { day: 5, name: "Day 5", details: "22 lunges, 3 sets, 20s rest", duration: 4 },
      { day: 6, name: "Day 6", details: "12 side lunges, 3 sets, 20s rest", duration: 3 },
      { day: 7, name: "Day 7", details: "24 lunges, 3 sets, 20s rest", duration: 5 },
      { day: 8, name: "Day 8", details: "14 side lunges, 3 sets, 20s rest", duration: 4 },
      { day: 9, name: "Day 9", details: "24 lunges, 3 sets, 20s rest", duration: 5 },
      { day: 10, name: "Day 10", details: "14 side lunges, 3 sets, 20s rest", duration: 4 },
      { day: 11, name: "Day 11", details: "24 lunges, 3 sets, 20s rest", duration: 5 },
      { day: 12, name: "Day 12", details: "14 side lunges, 3 sets, 20s rest", duration: 4 },
      { day: 13, name: "Day 13", details: "26 lunges, 3 sets, 20s rest", duration: 5 },
      { day: 14, name: "Day 14", details: "16 side lunges, 3 sets, 20s rest", duration: 4 },
      { day: 15, name: "Day 15", details: "26 lunges, 3 sets, 20s rest", duration: 5 },
      { day: 16, name: "Day 16", details: "16 side lunges, 3 sets, 20s rest", duration: 4 },
      { day: 17, name: "Day 17", details: "26 lunges, 3 sets, 20s rest", duration: 5 },
      { day: 18, name: "Day 18", details: "16 side lunges, 3 sets, 20s rest", duration: 4 },
      { day: 19, name: "Day 19", details: "28 lunges, 3 sets, 20s rest", duration: 6 },
      { day: 20, name: "Day 20", details: "18 side lunges, 3 sets, 20s rest", duration: 5 },
      { day: 21, name: "Day 21", details: "28 lunges, 3 sets, 20s rest", duration: 6 },
      { day: 22, name: "Day 22", details: "18 side lunges, 3 sets, 20s rest", duration: 5 },
      { day: 23, name: "Day 23", details: "28 lunges, 3 sets, 20s rest", duration: 6 },
      { day: 24, name: "Day 24", details: "18 side lunges, 3 sets, 20s rest", duration: 5 },
      { day: 25, name: "Day 25", details: "30 lunges, 3 sets, 20s rest", duration: 6 },
      { day: 26, name: "Day 26", details: "20 side lunges, 3 sets, 20s rest", duration: 5 },
      { day: 27, name: "Day 27", details: "30 lunges, 3 sets, 20s rest", duration: 6 },
      { day: 28, name: "Day 28", details: "20 side lunges, 3 sets, 20s rest", duration: 5 },
      { day: 29, name: "Day 29", details: "30 lunges, 3 sets, 20s rest", duration: 6 },
      { day: 30, name: "Day 30", details: "20 side lunges, 3 sets, 20s rest", duration: 5 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440007",
    title: "Calves of Steel Challenge",
    duration: 30,
    description: "A 30-day challenge for stronger, more defined calves. This challenge alternates between high-repetition calf raises and isometric holds to build endurance and strength. Calf raises can be done throughout the day.",
    estimatedTime: "5-10 min/day",
    difficulty: "Beginner",
    images: [
      { src: challengeAsset("calf-raises.png"), title: "Calf Raise" },
    ],
    exercises: [
        { day: 1, name: "Day 1", details: "60 calf raises in total throughout the day", duration: 3 },
        { day: 2, name: "Day 2", details: "20 seconds calf raise hold, 2 sets, 30sec rest", duration: 2 },
        { day: 3, name: "Day 3", details: "70 calf raises in total throughout the day", duration: 3 },
        { day: 4, name: "Day 4", details: "20 seconds calf raise hold, 2 sets, 30sec rest", duration: 2 },
        { day: 5, name: "Day 5", details: "80 calf raises in total throughout the day", duration: 4 },
        { day: 6, name: "Day 6", details: "30 seconds calf raise hold, 2 sets, 30sec rest", duration: 2 },
        { day: 7, name: "Day 7", details: "90 calf raises in total throughout the day", duration: 4 },
        { day: 8, name: "Day 8", details: "30 seconds calf raise hold, 2 sets, 30sec rest", duration: 2 },
        { day: 9, name: "Day 9", details: "100 calf raises in total throughout the day", duration: 5 },
        { day: 10, name: "Day 10", details: "40 seconds calf raise hold, 2 sets, 30sec rest", duration: 2 },
        { day: 11, name: "Day 11", details: "110 calf raises in total throughout the day", duration: 5 },
        { day: 12, name: "Day 12", details: "40 seconds calf raise hold, 2 sets, 30sec rest", duration: 2 },
        { day: 13, name: "Day 13", details: "120 calf raises in total throughout the day", duration: 6 },
        { day: 14, name: "Day 14", details: "50 seconds calf raise hold, 2 sets, 30sec rest", duration: 3 },
        { day: 15, name: "Day 15", details: "130 calf raises in total throughout the day", duration: 6 },
        { day: 16, name: "Day 16", details: "50 seconds calf raise hold, 2 sets, 30sec rest", duration: 3 },
        { day: 17, name: "Day 17", details: "140 calf raises in total throughout the day", duration: 7 },
        { day: 18, name: "Day 18", details: "60 seconds calf raise hold, 2 sets, 30sec rest", duration: 3 },
        { day: 19, name: "Day 19", details: "150 calf raises in total throughout the day", duration: 7 },
        { day: 20, name: "Day 20", details: "60 seconds calf raise hold, 2 sets, 30sec rest", duration: 3 },
        { day: 21, name: "Day 21", details: "160 calf raises in total throughout the day", duration: 8 },
        { day: 22, name: "Day 22", details: "1min 10sec calf raise hold, 2 sets, 30sec rest", duration: 3 },
        { day: 23, name: "Day 23", details: "170 calf raises in total throughout the day", duration: 8 },
        { day: 24, name: "Day 24", details: "1min 10sec calf raise hold, 2 sets, 30sec rest", duration: 3 },
        { day: 25, name: "Day 25", details: "180 calf raises in total throughout the day", duration: 9 },
        { day: 26, name: "Day 26", details: "1min 20sec calf raise hold, 2 sets, 30sec rest", duration: 4 },
        { day: 27, name: "Day 27", details: "190 calf raises in total throughout the day", duration: 9 },
        { day: 28, name: "Day 28", details: "1min 20sec calf raise hold, 2 sets, 30sec rest", duration: 4 },
        { day: 29, name: "Day 29", details: "200 calf raises in total throughout the day", duration: 10 },
        { day: 30, name: "Day 30", details: "1min 30sec calf raise hold, 2 sets, 30sec rest", duration: 4 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440008",
    title: "30-Day Plank Challenge",
    duration: 30,
    description: "A 30-day challenge to build core strength and endurance by holding a plank for increasing amounts of time.",
    estimatedTime: "< 5 min/day",
    difficulty: "Beginner",
    images: [
      { src: challengeAsset("plank.png"), title: "Plank" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "20 sec plank", duration: 1 },
      { day: 2, name: "Day 2", details: "20 sec plank", duration: 1 },
      { day: 3, name: "Day 3", details: "30 sec plank", duration: 1 },
      { day: 4, name: "Day 4", details: "30 sec plank", duration: 1 },
      { day: 5, name: "Day 5", details: "40 sec plank", duration: 1 },
      { day: 6, name: "Day 6", details: "Rest Day", duration: 0 },
      { day: 7, name: "Day 7", details: "45 sec plank", duration: 1 },
      { day: 8, name: "Day 8", details: "45 sec plank", duration: 1 },
      { day: 9, name: "Day 9", details: "1 min plank", duration: 1 },
      { day: 10, name: "Day 10", details: "1 min plank", duration: 1 },
      { day: 11, name: "Day 11", details: "1 min plank", duration: 1 },
      { day: 12, name: "Day 12", details: "1 min 30 sec plank", duration: 2 },
      { day: 13, name: "Day 13", details: "Rest Day", duration: 0 },
      { day: 14, name: "Day 14", details: "1 min 40 sec plank", duration: 2 },
      { day: 15, name: "Day 15", details: "1 min 50 sec plank", duration: 2 },
      { day: 16, name: "Day 16", details: "2 min plank", duration: 2 },
      { day: 17, name: "Day 17", details: "2 min plank", duration: 2 },
      { day: 18, name: "Day 18", details: "2 min 30 sec plank", duration: 3 },
      { day: 19, name: "Day 19", details: "Rest Day", duration: 0 },
      { day: 20, name: "Day 20", details: "2 min 30 sec plank", duration: 3 },
      { day: 21, name: "Day 21", details: "2 min 30 sec plank", duration: 3 },
      { day: 22, name: "Day 22", details: "3 min plank", duration: 3 },
      { day: 23, name: "Day 23", details: "3 min plank", duration: 3 },
      { day: 24, name: "Day 24", details: "3 min 30 sec plank", duration: 4 },
      { day: 25, name: "Day 25", details: "3 min 30 sec plank", duration: 4 },
      { day: 26, name: "Day 26", details: "Rest Day", duration: 0 },
      { day: 27, name: "Day 27", details: "4 min plank", duration: 4 },
      { day: 28, name: "Day 28", details: "4 min plank", duration: 4 },
      { day: 29, name: "Day 29", details: "4 min 30 sec plank", duration: 5 },
      { day: 30, name: "Day 30", details: "5 min plank", duration: 5 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440009",
    title: "Hollow Hold Challenge",
    duration: 30,
    description: "A 30-day challenge to master the hollow hold and superman hold, building a rock-solid core by alternating between two foundational gymnastic exercises.",
    estimatedTime: "< 5 min/day",
    difficulty: "Intermediate",
    images: [
      { src: challengeAsset("superman-hold.gif"), title: "Superman hold" },
      { src: challengeAsset("hollow-hold.gif"), title: "Hollow hold" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "20 seconds hollow hold", duration: 1 },
      { day: 2, name: "Day 2", details: "20 seconds superman hold", duration: 1 },
      { day: 3, name: "Day 3", details: "25 seconds hollow hold", duration: 1 },
      { day: 4, name: "Day 4", details: "25 seconds superman hold", duration: 1 },
      { day: 5, name: "Day 5", details: "30 seconds hollow hold", duration: 1 },
      { day: 6, name: "Day 6", details: "30 seconds superman hold", duration: 1 },
      { day: 7, name: "Day 7", details: "35 seconds hollow hold", duration: 1 },
      { day: 8, name: "Day 8", details: "35 seconds superman hold", duration: 1 },
      { day: 9, name: "Day 9", details: "40 seconds hollow hold", duration: 1 },
      { day: 10, name: "Day 10", details: "40 seconds superman hold", duration: 1 },
      { day: 11, name: "Day 11", details: "45 seconds hollow hold", duration: 1 },
      { day: 12, name: "Day 12", details: "45 seconds superman hold", duration: 1 },
      { day: 13, name: "Day 13", details: "50 seconds hollow hold", duration: 1 },
      { day: 14, name: "Day 14", details: "50 seconds superman hold", duration: 1 },
      { day: 15, name: "Day 15", details: "55 seconds hollow hold", duration: 1 },
      { day: 16, name: "Day 16", details: "55 seconds superman hold", duration: 1 },
      { day: 17, name: "Day 17", details: "60 seconds hollow hold", duration: 1 },
      { day: 18, name: "Day 18", details: "60 seconds superman hold", duration: 1 },
      { day: 19, name: "Day 19", details: "1min 10sec hollow hold", duration: 2 },
      { day: 20, name: "Day 20", details: "1min 10sec superman hold", duration: 2 },
      { day: 21, name: "Day 21", details: "1min 20sec hollow hold", duration: 2 },
      { day: 22, name: "Day 22", details: "1min 20sec superman hold", duration: 2 },
      { day: 23, name: "Day 23", details: "1min 30sec hollow hold", duration: 2 },
      { day: 24, name: "Day 24", details: "1min 30sec superman hold", duration: 2 },
      { day: 25, name: "Day 25", details: "1min 40sec hollow hold", duration: 2 },
      { day: 26, name: "Day 26", details: "1min 40sec superman hold", duration: 2 },
      { day: 27, name: "Day 27", details: "1min 50sec hollow hold", duration: 2 },
      { day: 28, name: "Day 28", details: "1min 50sec superman hold", duration: 2 },
      { day: 29, name: "Day 29", details: "2 minutes hollow hold", duration: 2 },
      { day: 30, name: "Day 30", details: "2 minutes superman hold", duration: 2 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440010",
    title: "The Long Run",
    duration: 30,
    description: "A 30-day challenge to build running endurance, progressing from 4 to 40 minutes. The plan includes a mix of running, walking, and sprinting to improve cardiovascular fitness.",
    estimatedTime: "4-40 min/day",
    difficulty: "Intermediate",
    images: [{ src: challengeAsset("walking-to-running.png"), title: "Running" }],
    exercises: [
      { day: 1, name: "Day 1", details: "4min run, 1min rest, repeat 2 times", duration: 10 },
      { day: 2, name: "Day 2", details: "5min run, 5min walk", duration: 10 },
      { day: 3, name: "Day 3", details: "5 x 10sec sprints", duration: 5 },
      { day: 4, name: "Day 4", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 5, name: "Day 5", details: "10min run", duration: 10 },
      { day: 6, name: "Day 6", details: "5min run, 5min walk", duration: 10 },
      { day: 7, name: "Day 7", details: "5 x 10sec sprints", duration: 5 },
      { day: 8, name: "Day 8", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 9, name: "Day 9", details: "15min run", duration: 15 },
      { day: 10, name: "Day 10", details: "5min run, 5min walk", duration: 10 },
      { day: 11, name: "Day 11", details: "5 x 10sec sprints", duration: 5 },
      { day: 12, name: "Day 12", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 13, name: "Day 13", details: "20min run", duration: 20 },
      { day: 14, name: "Day 14", details: "10min run, 10min walk", duration: 20 },
      { day: 15, name: "Day 15", details: "5 x 10sec sprints", duration: 5 },
      { day: 16, name: "Day 16", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 17, name: "Day 17", details: "25min run", duration: 25 },
      { day: 18, name: "Day 18", details: "10min run, 10min walk", duration: 20 },
      { day: 19, name: "Day 19", details: "5 x 10sec sprints", duration: 5 },
      { day: 20, name: "Day 20", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 21, name: "Day 21", details: "30min run", duration: 30 },
      { day: 22, name: "Day 22", details: "10min run, 10min walk", duration: 20 },
      { day: 23, name: "Day 23", details: "5 x 10sec sprints", duration: 5 },
      { day: 24, name: "Day 24", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 25, name: "Day 25", details: "35min run", duration: 35 },
      { day: 26, name: "Day 26", details: "15min run, 15min walk", duration: 30 },
      { day: 27, name: "Day 27", details: "5 x 10sec sprints", duration: 5 },
      { day: 28, name: "Day 28", details: "1min run, 1min walk, repeat 5 times", duration: 10 },
      { day: 29, name: "Day 29", details: "15min run, 15min walk", duration: 30 },
      { day: 30, name: "Day 30", details: "40min run", duration: 40 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440011",
    title: "Jump Rope 30-Day Challenge",
    duration: 30,
    description: "A 30-day challenge to improve cardio and coordination with a variety of jump rope workouts, including timed sets, non-stop skips, and total skips per day.",
    estimatedTime: "2-20 min/day",
    difficulty: "Intermediate",
    images: [
      { src: challengeAsset("jump-rope.png"), title: "Jump Rope" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "1 min skips, 1 min rest, 3 sets in total", duration: 6 },
      { day: 2, name: "Day 2", details: "4 min in total throughout the day", duration: 4 },
      { day: 3, name: "Day 3", details: "2 min skips non-stop", duration: 2 },
      { day: 4, name: "Day 4", details: "1 min skips, 1 min rest, 3 sets in total", duration: 6 },
      { day: 5, name: "Day 5", details: "200 skips one workout", duration: 4 },
      { day: 6, name: "Day 6", details: "1 min skips, 1 min rest, 3 sets in total", duration: 6 },
      { day: 7, name: "Day 7", details: "4 min in total throughout the day", duration: 4 },
      { day: 8, name: "Day 8", details: "2 min skips non-stop", duration: 2 },
      { day: 9, name: "Day 9", details: "1 min skips, 1 min rest, 3 sets in total", duration: 6 },
      { day: 10, name: "Day 10", details: "400 skips one workout", duration: 8 },
      { day: 11, name: "Day 11", details: "1 min skips, 1 min rest, 4 sets in total", duration: 8 },
      { day: 12, name: "Day 12", details: "6 min in total throughout the day", duration: 6 },
      { day: 13, name: "Day 13", details: "3 min skips non-stop", duration: 3 },
      { day: 14, name: "Day 14", details: "1 min skips, 1 min rest, 4 sets in total", duration: 8 },
      { day: 15, name: "Day 15", details: "450 skips one workout", duration: 9 },
      { day: 16, name: "Day 16", details: "1 min skips, 1 min rest, 4 sets in total", duration: 8 },
      { day: 17, name: "Day 17", details: "6 min in total throughout the day", duration: 6 },
      { day: 18, name: "Day 18", details: "3 min skips non-stop", duration: 3 },
      { day: 19, name: "Day 19", details: "1 min skips, 1 min rest, 4 sets in total", duration: 8 },
      { day: 20, name: "Day 20", details: "600 skips one workout", duration: 12 },
      { day: 21, name: "Day 21", details: "1 min skips, 1 min rest, 4 sets in total", duration: 8 },
      { day: 22, name: "Day 22", details: "8 min in total throughout the day", duration: 8 },
      { day: 23, name: "Day 23", details: "4 min skips non-stop", duration: 4 },
      { day: 24, name: "Day 24", details: "1 min skips, 1 min rest, 4 sets in total", duration: 8 },
      { day: 25, name: "Day 25", details: "800 skips one workout", duration: 16 },
      { day: 26, name: "Day 26", details: "1 min skips, 1 min rest, 5 sets in total", duration: 10 },
      { day: 27, name: "Day 27", details: "10 min in total throughout the day", duration: 10 },
      { day: 28, name: "Day 28", details: "4 min skips non-stop", duration: 4 },
      { day: 29, name: "Day 29", details: "1 min skips, 1 min rest, 5 sets in total", duration: 10 },
      { day: 30, name: "Day 30", details: "1000 skips one workout", duration: 20 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440012",
    title: "Wall-Sit 30-Day Challenge",
    duration: 30,
    description: "Progressive wall-sit holds with light recovery days. From Darebee; rest as needed between efforts.",
    estimatedTime: "1–5 min/day",
    difficulty: "Intermediate",
    images: [{ src: challengeAsset("wall-sit.png"), title: "Wall sit" }],
    exercises: [
      { day: 1, name: "Day 1", details: "20 seconds wall-sit", duration: 1 },
      { day: 2, name: "Day 2", details: "30 seconds wall-sit", duration: 2 },
      { day: 3, name: "Day 3", details: "40 seconds wall-sit", duration: 2 },
      { day: 4, name: "Day 4", details: "20 seconds wall-sit", duration: 1 },
      { day: 5, name: "Day 5", details: "50 seconds wall-sit", duration: 2 },
      { day: 6, name: "Day 6", details: "60 seconds wall-sit", duration: 2 },
      { day: 7, name: "Day 7", details: "1min 10sec wall-sit", duration: 2 },
      { day: 8, name: "Day 8", details: "20 seconds wall-sit", duration: 1 },
      { day: 9, name: "Day 9", details: "1min 20sec wall-sit", duration: 2 },
      { day: 10, name: "Day 10", details: "1min 30sec wall-sit", duration: 2 },
      { day: 11, name: "Day 11", details: "1min 40sec wall-sit", duration: 2 },
      { day: 12, name: "Day 12", details: "20 seconds wall-sit", duration: 1 },
      { day: 13, name: "Day 13", details: "1min 50sec wall-sit", duration: 2 },
      { day: 14, name: "Day 14", details: "2 minutes wall-sit", duration: 3 },
      { day: 15, name: "Day 15", details: "2min 10sec wall-sit", duration: 2 },
      { day: 16, name: "Day 16", details: "20 seconds wall-sit", duration: 1 },
      { day: 17, name: "Day 17", details: "2min 20sec wall-sit", duration: 2 },
      { day: 18, name: "Day 18", details: "2min 30sec wall-sit", duration: 2 },
      { day: 19, name: "Day 19", details: "2min 40sec wall-sit", duration: 2 },
      { day: 20, name: "Day 20", details: "20 seconds wall-sit", duration: 1 },
      { day: 21, name: "Day 21", details: "2min 50sec wall-sit", duration: 3 },
      { day: 22, name: "Day 22", details: "3 minutes wall-sit", duration: 4 },
      { day: 23, name: "Day 23", details: "3min 10sec wall-sit", duration: 4 },
      { day: 24, name: "Day 24", details: "20 seconds wall-sit", duration: 1 },
      { day: 25, name: "Day 25", details: "3min 20sec wall-sit", duration: 2 },
      { day: 26, name: "Day 26", details: "3min 30sec wall-sit", duration: 2 },
      { day: 27, name: "Day 27", details: "3min 40sec wall-sit", duration: 2 },
      { day: 28, name: "Day 28", details: "20 seconds wall-sit", duration: 1 },
      { day: 29, name: "Day 29", details: "3min 50sec wall-sit", duration: 2 },
      { day: 30, name: "Day 30", details: "4 minutes wall-sit", duration: 5 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440013",
    title: "50 Burpees in One Go Challenge",
    duration: 30,
    description: "Build up to 50 burpees in a single set. Multi-set days use 20 seconds rest between sets. From Darebee.",
    estimatedTime: "5–25 min/day",
    difficulty: "Advanced",
    images: [{ src: challengeAsset("burpees-50-one-go.png"), title: "Burpee" }],
    exercises: [
      { day: 1, name: "Day 1", details: "8 burpees, 4 burpees, 3 burpees, 3 burpees (20 sec rest between sets)", duration: 15 },
      { day: 2, name: "Day 2", details: "10 burpees in one go", duration: 3 },
      { day: 3, name: "Day 3", details: "8 burpees, 6 burpees, 3 burpees, 3 burpees (20 sec rest between sets)", duration: 15 },
      { day: 4, name: "Day 4", details: "14 burpees in one go", duration: 3 },
      { day: 5, name: "Day 5", details: "8 burpees, 6 burpees, 4 burpees, 4 burpees (20 sec rest between sets)", duration: 15 },
      { day: 6, name: "Day 6", details: "17 burpees in one go", duration: 4 },
      { day: 7, name: "Day 7", details: "8 burpees, 8 burpees, 4 burpees, 4 burpees (20 sec rest between sets)", duration: 15 },
      { day: 8, name: "Day 8", details: "20 burpees in one go", duration: 4 },
      { day: 9, name: "Day 9", details: "10 burpees, 8 burpees, 5 burpees, 5 burpees (20 sec rest between sets)", duration: 15 },
      { day: 10, name: "Day 10", details: "24 burpees in one go", duration: 5 },
      { day: 11, name: "Day 11", details: "10 burpees, 10 burpees, 5 burpees, 5 burpees (20 sec rest between sets)", duration: 15 },
      { day: 12, name: "Day 12", details: "26 burpees in one go", duration: 6 },
      { day: 13, name: "Day 13", details: "12 burpees, 10 burpees, 6 burpees, 6 burpees (20 sec rest between sets)", duration: 15 },
      { day: 14, name: "Day 14", details: "30 burpees in one go", duration: 6 },
      { day: 15, name: "Day 15", details: "12 burpees, 12 burpees, 6 burpees, 6 burpees (20 sec rest between sets)", duration: 15 },
      { day: 16, name: "Day 16", details: "33 burpees in one go", duration: 7 },
      { day: 17, name: "Day 17", details: "14 burpees, 12 burpees, 7 burpees, 7 burpees (20 sec rest between sets)", duration: 15 },
      { day: 18, name: "Day 18", details: "35 burpees in one go", duration: 7 },
      { day: 19, name: "Day 19", details: "14 burpees, 14 burpees, 7 burpees, 7 burpees (20 sec rest between sets)", duration: 15 },
      { day: 20, name: "Day 20", details: "37 burpees in one go", duration: 8 },
      { day: 21, name: "Day 21", details: "16 burpees, 14 burpees, 8 burpees, 8 burpees (20 sec rest between sets)", duration: 15 },
      { day: 22, name: "Day 22", details: "40 burpees in one go", duration: 8 },
      { day: 23, name: "Day 23", details: "16 burpees, 16 burpees, 8 burpees, 8 burpees (20 sec rest between sets)", duration: 15 },
      { day: 24, name: "Day 24", details: "42 burpees in one go", duration: 9 },
      { day: 25, name: "Day 25", details: "18 burpees, 16 burpees, 9 burpees, 9 burpees (20 sec rest between sets)", duration: 15 },
      { day: 26, name: "Day 26", details: "44 burpees in one go", duration: 9 },
      { day: 27, name: "Day 27", details: "18 burpees, 18 burpees, 9 burpees, 9 burpees (20 sec rest between sets)", duration: 15 },
      { day: 28, name: "Day 28", details: "47 burpees in one go", duration: 10 },
      { day: 29, name: "Day 29", details: "20 burpees, 18 burpees, 10 burpees, 10 burpees (20 sec rest between sets)", duration: 15 },
      { day: 30, name: "Day 30", details: "50 burpees in one go", duration: 10 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440014",
    title: "Ab 30-Day Challenge",
    duration: 30,
    description: "Daily crunches, leg raises, and plank holds that scale together. Reps can be spread throughout the day. From Neila Rey (neilarey.com).",
    estimatedTime: "12–41 min/day",
    difficulty: "Beginner",
    images: [
      { src: challengeAsset("ab-crunches.png"), title: "Crunches" },
      { src: challengeAsset("ab-leg-raises.png"), title: "Leg raises" },
      { src: challengeAsset("plank.png"), title: "Plank" },
    ],
    exercises: [
      { day: 1, name: "Day 1", details: "15 crunches, 6 leg raises, 10-sec plank (reps throughout the day)", duration: 12 },
      { day: 2, name: "Day 2", details: "20 crunches, 8 leg raises, 15-sec plank (reps throughout the day)", duration: 13 },
      { day: 3, name: "Day 3", details: "25 crunches, 10 leg raises, 20-sec plank (reps throughout the day)", duration: 14 },
      { day: 4, name: "Day 4", details: "30 crunches, 12 leg raises, 25-sec plank (reps throughout the day)", duration: 15 },
      { day: 5, name: "Day 5", details: "35 crunches, 14 leg raises, 30-sec plank (reps throughout the day)", duration: 16 },
      { day: 6, name: "Day 6", details: "40 crunches, 16 leg raises, 35-sec plank (reps throughout the day)", duration: 17 },
      { day: 7, name: "Day 7", details: "45 crunches, 18 leg raises, 40-sec plank (reps throughout the day)", duration: 18 },
      { day: 8, name: "Day 8", details: "50 crunches, 20 leg raises, 45-sec plank (reps throughout the day)", duration: 19 },
      { day: 9, name: "Day 9", details: "55 crunches, 22 leg raises, 50-sec plank (reps throughout the day)", duration: 20 },
      { day: 10, name: "Day 10", details: "60 crunches, 24 leg raises, 55-sec plank (reps throughout the day)", duration: 21 },
      { day: 11, name: "Day 11", details: "65 crunches, 26 leg raises, 60-sec plank (reps throughout the day)", duration: 22 },
      { day: 12, name: "Day 12", details: "70 crunches, 28 leg raises, 65-sec plank (reps throughout the day)", duration: 23 },
      { day: 13, name: "Day 13", details: "75 crunches, 30 leg raises, 70-sec plank (reps throughout the day)", duration: 24 },
      { day: 14, name: "Day 14", details: "80 crunches, 32 leg raises, 75-sec plank (reps throughout the day)", duration: 25 },
      { day: 15, name: "Day 15", details: "85 crunches, 34 leg raises, 80-sec plank (reps throughout the day)", duration: 26 },
      { day: 16, name: "Day 16", details: "90 crunches, 36 leg raises, 85-sec plank (reps throughout the day)", duration: 27 },
      { day: 17, name: "Day 17", details: "95 crunches, 38 leg raises, 90-sec plank (reps throughout the day)", duration: 28 },
      { day: 18, name: "Day 18", details: "100 crunches, 40 leg raises, 95-sec plank (reps throughout the day)", duration: 29 },
      { day: 19, name: "Day 19", details: "105 crunches, 42 leg raises, 100-sec plank (reps throughout the day)", duration: 30 },
      { day: 20, name: "Day 20", details: "110 crunches, 44 leg raises, 105-sec plank (reps throughout the day)", duration: 31 },
      { day: 21, name: "Day 21", details: "115 crunches, 46 leg raises, 110-sec plank (reps throughout the day)", duration: 33 },
      { day: 22, name: "Day 22", details: "120 crunches, 48 leg raises, 115-sec plank (reps throughout the day)", duration: 34 },
      { day: 23, name: "Day 23", details: "125 crunches, 50 leg raises, 120-sec plank (reps throughout the day)", duration: 35 },
      { day: 24, name: "Day 24", details: "130 crunches, 52 leg raises, 125-sec plank (reps throughout the day)", duration: 36 },
      { day: 25, name: "Day 25", details: "135 crunches, 54 leg raises, 130-sec plank (reps throughout the day)", duration: 37 },
      { day: 26, name: "Day 26", details: "140 crunches, 56 leg raises, 135-sec plank (reps throughout the day)", duration: 38 },
      { day: 27, name: "Day 27", details: "145 crunches, 58 leg raises, 140-sec plank (reps throughout the day)", duration: 39 },
      { day: 28, name: "Day 28", details: "150 crunches, 60 leg raises, 145-sec plank (reps throughout the day)", duration: 40 },
      { day: 29, name: "Day 29", details: "155 crunches, 62 leg raises, 150-sec plank (reps throughout the day)", duration: 41 },
      { day: 30, name: "Day 30", details: "160 crunches, 64 leg raises, 155-sec plank (reps throughout the day)", duration: 41 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440015",
    title: "Plank Variations Challenge (MyFitnessPal)",
    duration: 30,
    description: "Four-week style plan with standard, side, walking, Spiderman, and alternating-hand planks; includes rest and test days. REST A–E legend: A = as needed; B = ≤45s; C = <1 min; D = 1 min; E = 90s between sets. Based on MyFitnessPal infographic.",
    estimatedTime: "5–35 min/day",
    difficulty: "Intermediate",
    images: [{ src: challengeAsset("plank.png"), title: "Plank variations" }],
    exercises: [
      { day: 1, name: "Day 1", details: "Plank: establish baseline max hold with good form", duration: 8 },
      { day: 2, name: "Day 2", details: "Plank 10–30s, REST A (as needed), repeat 3x", duration: 8 },
      { day: 3, name: "Day 3", details: "Rest day", duration: 0 },
      { day: 4, name: "Day 4", details: "Plank 10–30s, REST A, repeat 4x", duration: 8 },
      { day: 5, name: "Day 5", details: "Side plank both sides 10–30s, REST A, 3x per side", duration: 8 },
      { day: 6, name: "Day 6", details: "Rest day", duration: 0 },
      { day: 7, name: "Day 7", details: "Test: max plank hold with good form", duration: 8 },
      { day: 8, name: "Day 8", details: "Plank 15–35s, REST B (≤45s between sets), repeat 5x", duration: 8 },
      { day: 9, name: "Day 9", details: "Side plank 15–35s, REST B, 4x per side", duration: 8 },
      { day: 10, name: "Day 10", details: "Plank 20–40s, REST C (<1 min between sets), repeat 6x", duration: 8 },
      { day: 11, name: "Day 11", details: "Rest day", duration: 0 },
      { day: 12, name: "Day 12", details: "Plank 25–45s, REST C, 4x; Side plank 20–40s, REST C, 3x", duration: 12 },
      { day: 13, name: "Day 13", details: "Rest day", duration: 0 },
      { day: 14, name: "Day 14", details: "Test: max plank hold", duration: 8 },
      { day: 15, name: "Day 15", details: "Plank 30–50s, REST B, 5x; Side plank 25–45s, REST B, 5x", duration: 12 },
      { day: 16, name: "Day 16", details: "Walking plank 10–30s, REST D (1 min rest), 4x; Plank 35–55s, REST C, 3x", duration: 12 },
      { day: 17, name: "Day 17", details: "Rest day", duration: 0 },
      { day: 18, name: "Day 18", details: "Walking plank 15–35s, REST D, 5x; Side plank 25–45s, REST B, 5x", duration: 12 },
      { day: 19, name: "Day 19", details: "Plank 40–60s, REST D, 6–8x", duration: 8 },
      { day: 20, name: "Day 20", details: "Rest day", duration: 0 },
      { day: 21, name: "Day 21", details: "Test: max plank hold", duration: 8 },
      { day: 22, name: "Day 22", details: "Spiderman plank 15–30s, REST B, 4x; Side plank 30–50s, REST B, 6x; Plank 45–65s, REST D, 4x", duration: 16 },
      { day: 23, name: "Day 23", details: "Alternating hand plank 15–30s, REST D, 4x; Walking plank 20–40s, REST D, 4x; Plank 30–45s, REST B, 3x", duration: 16 },
      { day: 24, name: "Day 24", details: "Spiderman plank 20–35s, REST D, 5x; Side plank 35–55s, REST D, 4x; Plank 50–70s, REST D, 2x", duration: 16 },
      { day: 25, name: "Day 25", details: "Rest day", duration: 0 },
      { day: 26, name: "Day 26", details: "Alternating hand plank 20–35s, REST D, 5x; Spiderman plank 25–40s, REST D, 3x; Plank 55–75s, REST E (90s), 2x", duration: 16 },
      { day: 27, name: "Day 27", details: "Rest day", duration: 0 },
      { day: 28, name: "Day 28", details: "Side plank 40–60s, REST D, 4x; Alternating hand plank 25–40s, REST D, 6x", duration: 12 },
      { day: 29, name: "Day 29", details: "Rest day", duration: 0 },
      { day: 30, name: "Day 30", details: "Test: max plank hold", duration: 8 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440016",
    title: "Tricep Dips 30-Day Challenge",
    duration: 30,
    description: "Alternating volume days and isometric dip holds. From Darebee.",
    estimatedTime: "5–15 min/day",
    difficulty: "Intermediate",
    images: [{ src: challengeAsset("tricep-dips.png"), title: "Tricep dips" }],
    exercises: [
      { day: 1, name: "Day 1", details: "6 tricep dips, 3 sets, 30 seconds rest between sets", duration: 14 },
      { day: 2, name: "Day 2", details: "20 seconds tricep dip hold", duration: 4 },
      { day: 3, name: "Day 3", details: "6 tricep dips, 4 sets, 30 seconds rest between sets", duration: 14 },
      { day: 4, name: "Day 4", details: "20 seconds tricep dip hold", duration: 4 },
      { day: 5, name: "Day 5", details: "8 tricep dips, 3 sets, 30 seconds rest between sets", duration: 14 },
      { day: 6, name: "Day 6", details: "30 seconds tricep dip hold", duration: 4 },
      { day: 7, name: "Day 7", details: "8 tricep dips, 4 sets, 30 seconds rest between sets", duration: 14 },
      { day: 8, name: "Day 8", details: "30 seconds tricep dip hold", duration: 4 },
      { day: 9, name: "Day 9", details: "10 tricep dips, 3 sets, 30 seconds rest between sets", duration: 14 },
      { day: 10, name: "Day 10", details: "40 seconds tricep dip hold", duration: 4 },
      { day: 11, name: "Day 11", details: "10 tricep dips, 4 sets, 30 seconds rest between sets", duration: 14 },
      { day: 12, name: "Day 12", details: "40 seconds tricep dip hold", duration: 4 },
      { day: 13, name: "Day 13", details: "12 tricep dips, 3 sets, 30 seconds rest between sets", duration: 14 },
      { day: 14, name: "Day 14", details: "50 seconds tricep dip hold", duration: 4 },
      { day: 15, name: "Day 15", details: "12 tricep dips, 4 sets, 30 seconds rest between sets", duration: 14 },
      { day: 16, name: "Day 16", details: "50 seconds tricep dip hold", duration: 4 },
      { day: 17, name: "Day 17", details: "14 tricep dips, 3 sets, 30 seconds rest between sets", duration: 14 },
      { day: 18, name: "Day 18", details: "60 seconds tricep dip hold", duration: 4 },
      { day: 19, name: "Day 19", details: "14 tricep dips, 4 sets, 30 seconds rest between sets", duration: 14 },
      { day: 20, name: "Day 20", details: "60 seconds tricep dip hold", duration: 4 },
      { day: 21, name: "Day 21", details: "16 tricep dips, 3 sets, 30 seconds rest between sets", duration: 14 },
      { day: 22, name: "Day 22", details: "1 min 10 sec tricep dip hold", duration: 4 },
      { day: 23, name: "Day 23", details: "16 tricep dips, 4 sets, 30 seconds rest between sets", duration: 14 },
      { day: 24, name: "Day 24", details: "1 min 10 sec tricep dip hold", duration: 4 },
      { day: 25, name: "Day 25", details: "18 tricep dips, 3 sets, 30 seconds rest between sets", duration: 14 },
      { day: 26, name: "Day 26", details: "1 min 20 sec tricep dip hold", duration: 4 },
      { day: 27, name: "Day 27", details: "18 tricep dips, 4 sets, 30 seconds rest between sets", duration: 14 },
      { day: 28, name: "Day 28", details: "1 min 20 sec tricep dip hold", duration: 4 },
      { day: 29, name: "Day 29", details: "20 tricep dips, 3 sets, 30 seconds rest between sets", duration: 14 },
      { day: 30, name: "Day 30", details: "1 min 30 sec tricep dip hold", duration: 4 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440017",
    title: "Squats 30-Day Challenge",
    duration: 30,
    description: "Three squat sets most days with wall sits on recovery markers. 60 seconds rest between squat sets. From Neila Rey (neilarey.com).",
    estimatedTime: "10–25 min/day",
    difficulty: "Beginner",
    images: [{ src: challengeAsset("squats.png"), title: "Squats" }],
    exercises: [
      { day: 1, name: "Day 1", details: "10 reps | 6 reps | 6 reps (squats; 60 sec rest between sets)", duration: 18 },
      { day: 2, name: "Day 2", details: "16 reps | 10 reps | 10 reps", duration: 18 },
      { day: 3, name: "Day 3", details: "18 reps | 10 reps | 10 reps", duration: 18 },
      { day: 4, name: "Day 4", details: "20 reps | 6 reps | 6 reps", duration: 18 },
      { day: 5, name: "Day 5", details: "30sec wall sit", duration: 2 },
      { day: 6, name: "Day 6", details: "22 reps | 6 reps | 6 reps", duration: 18 },
      { day: 7, name: "Day 7", details: "24 reps | 10 reps | 10 reps", duration: 18 },
      { day: 8, name: "Day 8", details: "26 reps | 10 reps | 10 reps", duration: 18 },
      { day: 9, name: "Day 9", details: "28 reps | 6 reps | 6 reps", duration: 18 },
      { day: 10, name: "Day 10", details: "40sec wall sit", duration: 2 },
      { day: 11, name: "Day 11", details: "30 reps | 6 reps | 6 reps", duration: 18 },
      { day: 12, name: "Day 12", details: "32 reps | 10 reps | 10 reps", duration: 18 },
      { day: 13, name: "Day 13", details: "34 reps | 10 reps | 10 reps", duration: 18 },
      { day: 14, name: "Day 14", details: "36 reps | 10 reps | 10 reps", duration: 18 },
      { day: 15, name: "Day 15", details: "1 minute wall sit", duration: 2 },
      { day: 16, name: "Day 16", details: "38 reps | 6 reps | 6 reps", duration: 18 },
      { day: 17, name: "Day 17", details: "40 reps | 10 reps | 10 reps", duration: 18 },
      { day: 18, name: "Day 18", details: "42 reps | 10 reps | 10 reps", duration: 18 },
      { day: 19, name: "Day 19", details: "44 reps | 6 reps | 6 reps", duration: 18 },
      { day: 20, name: "Day 20", details: "1min 20sec wall sit", duration: 3 },
      { day: 21, name: "Day 21", details: "46 reps | 6 reps | 6 reps", duration: 18 },
      { day: 22, name: "Day 22", details: "48 reps | 10 reps | 10 reps", duration: 18 },
      { day: 23, name: "Day 23", details: "50 reps | 10 reps | 10 reps", duration: 18 },
      { day: 24, name: "Day 24", details: "52 reps | 6 reps | 6 reps", duration: 18 },
      { day: 25, name: "Day 25", details: "1min 40sec wall sit", duration: 3 },
      { day: 26, name: "Day 26", details: "54 reps | 6 reps | 6 reps", duration: 18 },
      { day: 27, name: "Day 27", details: "56 reps | 10 reps | 10 reps", duration: 18 },
      { day: 28, name: "Day 28", details: "58 reps | 10 reps | 10 reps", duration: 18 },
      { day: 29, name: "Day 29", details: "2 minutes wall sit", duration: 4 },
      { day: 30, name: "Day 30", details: "60 reps | 20 reps | 20 reps", duration: 18 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440018",
    title: "From Walking to Running in 30 Days",
    duration: 30,
    description: "Walk–run intervals building toward longer runs; includes easy walk-only days. From Neila Rey (neilarey.com).",
    estimatedTime: "12–45 min/day",
    difficulty: "Beginner",
    images: [{ src: challengeAsset("walking-to-running.png"), title: "Walk to run" }],
    exercises: [
      { day: 1, name: "Day 1", details: "4 min walk, 1 min run; repeat 3 times", duration: 15 },
      { day: 2, name: "Day 2", details: "4 min walk, 1 min run; repeat 4 times", duration: 20 },
      { day: 3, name: "Day 3", details: "2 min walk, 2 min run; repeat 2 times", duration: 8 },
      { day: 4, name: "Day 4", details: "15 min walk", duration: 15 },
      { day: 5, name: "Day 5", details: "1 min walk, 10 sec sprint; repeat 5 times", duration: 12 },
      { day: 6, name: "Day 6", details: "2 min walk, 2 min run; repeat 3 times", duration: 12 },
      { day: 7, name: "Day 7", details: "3 min walk, 2 min run; repeat 3 times", duration: 15 },
      { day: 8, name: "Day 8", details: "15 min walk", duration: 15 },
      { day: 9, name: "Day 9", details: "2 min walk, 2 min run; repeat 4 times", duration: 16 },
      { day: 10, name: "Day 10", details: "2 min walk, 10 sec sprint; repeat 5 times", duration: 12 },
      { day: 11, name: "Day 11", details: "5 min walk, 2 min run; repeat 4 times", duration: 28 },
      { day: 12, name: "Day 12", details: "15 min walk", duration: 15 },
      { day: 13, name: "Day 13", details: "2 min walk, 3 min run; repeat 3 times", duration: 15 },
      { day: 14, name: "Day 14", details: "2 min walk, 2 min run; repeat 4 times", duration: 16 },
      { day: 15, name: "Day 15", details: "2 min walk, 20 sec sprint; repeat 5 times", duration: 12 },
      { day: 16, name: "Day 16", details: "15 min walk", duration: 15 },
      { day: 17, name: "Day 17", details: "3 min walk, 3 min run; repeat 4 times", duration: 24 },
      { day: 18, name: "Day 18", details: "2 min walk, 3 min run; repeat 4 times", duration: 20 },
      { day: 19, name: "Day 19", details: "3 min walk, 3 min run; repeat 5 times", duration: 30 },
      { day: 20, name: "Day 20", details: "15 min walk", duration: 15 },
      { day: 21, name: "Day 21", details: "1 min walk, 1 min run; repeat 5 times", duration: 10 },
      { day: 22, name: "Day 22", details: "1 min walk, 2 min run; repeat 3 times", duration: 9 },
      { day: 23, name: "Day 23", details: "1 min walk, 3 min run; repeat 3 times", duration: 12 },
      { day: 24, name: "Day 24", details: "15 min walk", duration: 15 },
      { day: 25, name: "Day 25", details: "2 min walk, 25 sec sprint; repeat 5 times", duration: 12 },
      { day: 26, name: "Day 26", details: "1 min walk, 4 min run; repeat 3 times", duration: 15 },
      { day: 27, name: "Day 27", details: "2 min walk, 4 min run; repeat 4 times", duration: 24 },
      { day: 28, name: "Day 28", details: "15 min walk", duration: 15 },
      { day: 29, name: "Day 29", details: "2 min walk, 5 min run; repeat 5 times", duration: 35 },
      { day: 30, name: "Day 30", details: "1 min walk, 5 min run; repeat 6 times", duration: 36 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440019",
    title: "Pull-Up Progression Challenge",
    duration: 30,
    description: "Build from zero to 10 consecutive pull-ups with progressive strength training for your back, biceps, and grip.",
    estimatedTime: "5-15 min/day",
    difficulty: "Intermediate",
    images: [
      { src: challengeAsset("pull-ups.png"), title: "Pull-up" },
    ],
    exercises: [
      { day: 1, name: "Dead Hang", details: "20 sec dead hang, 3 sets, 60s rest", duration: 5 },
      { day: 2, name: "Dead Hang", details: "25 sec dead hang, 3 sets, 60s rest", duration: 5 },
      { day: 3, name: "Dead Hang", details: "30 sec dead hang, 3 sets, 60s rest", duration: 5 },
      { day: 4, name: "Scapular Pull-ups", details: "5 scapular pull-ups, 3 sets, 60s rest", duration: 6 },
      { day: 5, name: "Scapular Pull-ups", details: "6 scapular pull-ups, 3 sets, 60s rest", duration: 6 },
      { day: 6, name: "Scapular Pull-ups", details: "8 scapular pull-ups, 3 sets, 60s rest", duration: 7 },
      { day: 7, name: "Negative Pull-ups", details: "3 negatives, 5-sec descent, 3 sets", duration: 8 },
      { day: 8, name: "Negative Pull-ups", details: "4 negatives, 5-sec descent, 3 sets", duration: 9 },
      { day: 9, name: "Negative Pull-ups", details: "5 negatives, 5-sec descent, 3 sets", duration: 10 },
      { day: 10, name: "Assisted Pull-ups", details: "3 assisted pull-ups, 3 sets, 90s rest", duration: 8 },
      { day: 11, name: "Assisted Pull-ups", details: "4 assisted pull-ups, 3 sets, 90s rest", duration: 9 },
      { day: 12, name: "Assisted Pull-ups", details: "5 assisted pull-ups, 3 sets, 90s rest", duration: 10 },
      { day: 13, name: "First Pull-up", details: "1 full pull-up + 3 negatives, 3 sets", duration: 10 },
      { day: 14, name: "First Pull-up", details: "1 full pull-up + 3 negatives, 4 sets", duration: 11 },
      { day: 15, name: "Building Up", details: "2 pull-ups, 3 sets, 90s rest", duration: 10 },
      { day: 16, name: "Building Up", details: "2 pull-ups, 4 sets, 90s rest", duration: 11 },
      { day: 17, name: "Building Up", details: "3 pull-ups, 3 sets, 90s rest", duration: 12 },
      { day: 18, name: "Building Up", details: "3 pull-ups, 4 sets, 90s rest", duration: 13 },
      { day: 19, name: "Pushing Forward", details: "4 pull-ups, 3 sets, 90s rest", duration: 12 },
      { day: 20, name: "Pushing Forward", details: "5 pull-ups, 3 sets, 90s rest", duration: 13 },
      { day: 21, name: "Halfway There", details: "5 pull-ups, 4 sets, 90s rest", duration: 14 },
      { day: 22, name: "Getting Stronger", details: "6 pull-ups, 3 sets, 90s rest", duration: 13 },
      { day: 23, name: "Getting Stronger", details: "7 pull-ups, 3 sets, 90s rest", duration: 14 },
      { day: 24, name: "Almost There", details: "7 pull-ups, 4 sets, 90s rest", duration: 15 },
      { day: 25, name: "Almost There", details: "8 pull-ups, 3 sets, 90s rest", duration: 14 },
      { day: 26, name: "Pushing Limits", details: "8 pull-ups, 4 sets, 90s rest", duration: 15 },
      { day: 27, name: "Pushing Limits", details: "9 pull-ups, 3 sets, 90s rest", duration: 15 },
      { day: 28, name: "One Away", details: "9 pull-ups, 4 sets, 90s rest", duration: 15 },
      { day: 29, name: "Rest Day", details: "Rest Day - prep for the final test", duration: 0 },
      { day: 30, name: "Day 30", details: "10 consecutive pull-ups", duration: 5 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440020",
    title: "Glute Bridge Challenge",
    duration: 30,
    description: "Activate and strengthen your glutes and posterior chain with progressive bridge variations.",
    estimatedTime: "8-18 min/day",
    difficulty: "Beginner",
    images: [
      { src: challengeAsset("glute-bridge.png"), title: "Glute Bridge" },
    ],
    exercises: [
      { day: 1, name: "Basic Bridge", details: "20 glute bridges, 2 sets, 30s rest", duration: 8 },
      { day: 2, name: "Basic Bridge", details: "25 glute bridges, 2 sets, 30s rest", duration: 9 },
      { day: 3, name: "Basic Bridge", details: "30 glute bridges, 2 sets, 30s rest", duration: 10 },
      { day: 4, name: "Single-Leg Bridge", details: "10 each leg, 2 sets, 30s rest", duration: 10 },
      { day: 5, name: "Single-Leg Bridge", details: "12 each leg, 2 sets, 30s rest", duration: 11 },
      { day: 6, name: "Single-Leg Bridge", details: "15 each leg, 2 sets, 30s rest", duration: 12 },
      { day: 7, name: "Bridge March", details: "20 bridge marches, 2 sets, 30s rest", duration: 10 },
      { day: 8, name: "Bridge March", details: "25 bridge marches, 2 sets, 30s rest", duration: 11 },
      { day: 9, name: "Bridge March", details: "30 bridge marches, 2 sets, 30s rest", duration: 12 },
      { day: 10, name: "Frog Pump", details: "25 frog pumps, 2 sets, 30s rest", duration: 10 },
      { day: 11, name: "Frog Pump", details: "30 frog pumps, 2 sets, 30s rest", duration: 11 },
      { day: 12, name: "Frog Pump", details: "35 frog pumps, 2 sets, 30s rest", duration: 12 },
      { day: 13, name: "Elevated Bridge", details: "15 elevated bridges, 3 sets, 30s rest", duration: 12 },
      { day: 14, name: "Elevated Bridge", details: "18 elevated bridges, 3 sets, 30s rest", duration: 13 },
      { day: 15, name: "Elevated Bridge", details: "20 elevated bridges, 3 sets, 30s rest", duration: 14 },
      { day: 16, name: "Single-Leg Elevated", details: "8 each leg, 2 sets, 30s rest", duration: 12 },
      { day: 17, name: "Single-Leg Elevated", details: "10 each leg, 2 sets, 30s rest", duration: 13 },
      { day: 18, name: "Single-Leg Elevated", details: "12 each leg, 2 sets, 30s rest", duration: 14 },
      { day: 19, name: "Bridge Hold", details: "30 sec hold, 3 sets, 30s rest", duration: 10 },
      { day: 20, name: "Bridge Hold", details: "40 sec hold, 3 sets, 30s rest", duration: 11 },
      { day: 21, name: "Bridge Hold", details: "45 sec hold, 3 sets, 30s rest", duration: 12 },
      { day: 22, name: "Bridge Pulse", details: "20 reps + 10 pulses, 2 sets", duration: 12 },
      { day: 23, name: "Bridge Pulse", details: "25 reps + 10 pulses, 2 sets", duration: 13 },
      { day: 24, name: "Bridge Pulse", details: "30 reps + 15 pulses, 2 sets", duration: 14 },
      { day: 25, name: "Reverse Hyper Hold", details: "20 sec hold, 3 sets, 30s rest", duration: 10 },
      { day: 26, name: "Reverse Hyper Hold", details: "25 sec hold, 3 sets, 30s rest", duration: 11 },
      { day: 27, name: "Reverse Hyper Hold", details: "30 sec hold, 3 sets, 30s rest", duration: 12 },
      { day: 28, name: "Single-Leg Hold", details: "15 sec each leg, 3 sets", duration: 12 },
      { day: 29, name: "Single-Leg Hold", details: "20 sec each leg, 3 sets", duration: 13 },
      { day: 30, name: "Day 30", details: "50 glute bridges + 30 sec hold", duration: 18 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440021",
    title: "Flexibility & Mobility Challenge",
    duration: 30,
    description: "Improve full-body flexibility, joint mobility, and injury prevention with daily targeted stretching routines.",
    estimatedTime: "15-25 min/day",
    difficulty: "Beginner",
    images: [
      { src: challengeAsset("stretching.png"), title: "Stretching" },
    ],
    exercises: [
      { day: 1, name: "Foundation Flow", details: "Hamstring 60s/side, hip flexor 45s/side, cat-cow 10 reps", duration: 15 },
      { day: 2, name: "Foundation Flow", details: "Child's pose 60s, thoracic rotation 8/side, hamstring 60s/side", duration: 15 },
      { day: 3, name: "Foundation Flow", details: "Hip flexor 45s/side, cat-cow 10 reps, child's pose 60s", duration: 15 },
      { day: 4, name: "Foundation Flow", details: "Full foundation circuit x 2 rounds", duration: 18 },
      { day: 5, name: "Foundation Flow", details: "Full foundation circuit x 2 rounds", duration: 18 },
      { day: 6, name: "Foundation Flow", details: "Hold longest stretches 90s each", duration: 20 },
      { day: 7, name: "Foundation Flow", details: "Full foundation flow, slow and mindful", duration: 20 },
      { day: 8, name: "Lower Body", details: "Pigeon pose 60s/side, butterfly 60s, quad 45s/side", duration: 16 },
      { day: 9, name: "Lower Body", details: "Calf stretch 30s/side, 90/90 hip 45s/side, pigeon 60s/side", duration: 16 },
      { day: 10, name: "Lower Body", details: "Butterfly 60s, quad 45s/side, calf 30s/side, 90/90 45s/side", duration: 16 },
      { day: 11, name: "Lower Body", details: "Full lower body circuit x 2 rounds", duration: 18 },
      { day: 12, name: "Lower Body", details: "Full lower body circuit x 2 rounds", duration: 18 },
      { day: 13, name: "Lower Body", details: "Hold all stretches 90s each", duration: 20 },
      { day: 14, name: "Lower Body", details: "Deep lower body flow, slow and mindful", duration: 20 },
      { day: 15, name: "Upper Body", details: "Shoulder cross-body 45s/side, tricep 30s/side, chest opener 60s", duration: 15 },
      { day: 16, name: "Upper Body", details: "Neck rolls 10 each, wrist flexor 30s/side, shoulder 45s/side", duration: 15 },
      { day: 17, name: "Upper Body", details: "Chest opener 60s, tricep 30s/side, neck rolls 10 each", duration: 15 },
      { day: 18, name: "Upper Body", details: "Full upper body circuit x 2 rounds", duration: 18 },
      { day: 19, name: "Upper Body", details: "Full upper body circuit x 2 rounds", duration: 18 },
      { day: 20, name: "Upper Body", details: "Hold all stretches 90s each", duration: 20 },
      { day: 21, name: "Upper Body", details: "Deep upper body flow, slow and mindful", duration: 20 },
      { day: 22, name: "Integration", details: "World's greatest stretch 5/side, inchworm 8 reps", duration: 18 },
      { day: 23, name: "Integration", details: "Deep squat hold 60s, couch stretch 45s/side", duration: 18 },
      { day: 24, name: "Integration", details: "Frog stretch 60s, world's greatest 5/side, inchworm 8", duration: 18 },
      { day: 25, name: "Integration", details: "Full integration circuit x 2 rounds", duration: 20 },
      { day: 26, name: "Integration", details: "Full integration circuit x 2 rounds", duration: 20 },
      { day: 27, name: "Integration", details: "Hold all stretches 90s each", duration: 22 },
      { day: 28, name: "Integration", details: "Deep integration flow, slow and mindful", duration: 22 },
      { day: 29, name: "Full Body Flow", details: "Complete all stretches from weeks 1-4, 60s each", duration: 25 },
      { day: 30, name: "Full Body Flow", details: "Complete all stretches from weeks 1-4, 90s each", duration: 25 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440022",
    title: "Mountain Climber 30-Day Challenge",
    duration: 30,
    description: "Progressive mountain climber challenge building core endurance and cardio stamina from 30 to 200 reps per day.",
    estimatedTime: "5-15 min/day",
    difficulty: "Intermediate",
    images: [{ src: challengeAsset("plank.png"), title: "Mountain climbers" }],
    exercises: [
      { day: 1, name: "Day 1", details: "30 mountain climbers, 3 sets, 30s rest", duration: 5 },
      { day: 2, name: "Day 2", details: "40 mountain climbers, 3 sets, 30s rest", duration: 5 },
      { day: 3, name: "Day 3", details: "50 mountain climbers, 3 sets, 30s rest", duration: 6 },
      { day: 4, name: "Day 4", details: "30 mountain climbers, 3 sets, 30s rest", duration: 5 },
      { day: 5, name: "Day 5", details: "60 mountain climbers, 3 sets, 30s rest", duration: 7 },
      { day: 6, name: "Day 6", details: "70 mountain climbers, 3 sets, 30s rest", duration: 7 },
      { day: 7, name: "Day 7", details: "80 mountain climbers, 3 sets, 30s rest", duration: 8 },
      { day: 8, name: "Day 8", details: "40 mountain climbers, 3 sets, 30s rest", duration: 5 },
      { day: 9, name: "Day 9", details: "90 mountain climbers, 3 sets, 30s rest", duration: 8 },
      { day: 10, name: "Day 10", details: "100 mountain climbers, 3 sets, 30s rest", duration: 9 },
      { day: 11, name: "Day 11", details: "110 mountain climbers, 3 sets, 30s rest", duration: 9 },
      { day: 12, name: "Day 12", details: "50 mountain climbers, 3 sets, 30s rest", duration: 6 },
      { day: 13, name: "Day 13", details: "120 mountain climbers, 3 sets, 30s rest", duration: 10 },
      { day: 14, name: "Day 14", details: "130 mountain climbers, 3 sets, 30s rest", duration: 10 },
      { day: 15, name: "Day 15", details: "140 mountain climbers, 3 sets, 30s rest", duration: 11 },
      { day: 16, name: "Day 16", details: "60 mountain climbers, 3 sets, 30s rest", duration: 6 },
      { day: 17, name: "Day 17", details: "150 mountain climbers, 3 sets, 30s rest", duration: 11 },
      { day: 18, name: "Day 18", details: "160 mountain climbers, 3 sets, 30s rest", duration: 12 },
      { day: 19, name: "Day 19", details: "170 mountain climbers, 3 sets, 30s rest", duration: 12 },
      { day: 20, name: "Day 20", details: "70 mountain climbers, 3 sets, 30s rest", duration: 7 },
      { day: 21, name: "Day 21", details: "180 mountain climbers, 3 sets, 30s rest", duration: 13 },
      { day: 22, name: "Day 22", details: "190 mountain climbers, 3 sets, 30s rest", duration: 13 },
      { day: 23, name: "Day 23", details: "200 mountain climbers, 3 sets, 30s rest", duration: 14 },
      { day: 24, name: "Day 24", details: "80 mountain climbers, 3 sets, 30s rest", duration: 7 },
      { day: 25, name: "Day 25", details: "200 mountain climbers, 3 sets, 30s rest", duration: 14 },
      { day: 26, name: "Day 26", details: "200 mountain climbers, 3 sets, 30s rest", duration: 14 },
      { day: 27, name: "Day 27", details: "200 mountain climbers, 3 sets, 30s rest", duration: 14 },
      { day: 28, name: "Day 28", details: "90 mountain climbers, 3 sets, 30s rest", duration: 8 },
      { day: 29, name: "Day 29", details: "200 mountain climbers, 3 sets, 30s rest", duration: 14 },
      { day: 30, name: "Day 30", details: "200 mountain climbers in one go", duration: 15 },
    ],
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440023",
    title: "Handstand Progression Challenge",
    duration: 30,
    description: "Build shoulder strength and balance working toward a freestanding handstand through progressive drills.",
    estimatedTime: "10-20 min/day",
    difficulty: "Advanced",
    images: [
      { src: challengeAsset("handstand.png"), title: "Handstand" },
    ],
    exercises: [
      { day: 1, name: "Wall Walks", details: "5 wall walks, 3 sets, 60s rest", duration: 10 },
      { day: 2, name: "Wall Walks", details: "6 wall walks, 3 sets, 60s rest", duration: 10 },
      { day: 3, name: "Wall Walks", details: "8 wall walks, 3 sets, 60s rest", duration: 12 },
      { day: 4, name: "Wall Hold", details: "15 sec chest-to-wall hold, 3 sets", duration: 10 },
      { day: 5, name: "Wall Hold", details: "20 sec chest-to-wall hold, 3 sets", duration: 10 },
      { day: 6, name: "Wall Hold", details: "25 sec chest-to-wall hold, 3 sets", duration: 12 },
      { day: 7, name: "Wall Hold", details: "30 sec chest-to-wall hold, 3 sets", duration: 12 },
      { day: 8, name: "Shoulder Taps", details: "10 wall shoulder taps, 3 sets, 60s rest", duration: 10 },
      { day: 9, name: "Shoulder Taps", details: "12 wall shoulder taps, 3 sets, 60s rest", duration: 10 },
      { day: 10, name: "Shoulder Taps", details: "15 wall shoulder taps, 3 sets, 60s rest", duration: 12 },
      { day: 11, name: "Wall Hold", details: "40 sec chest-to-wall hold, 3 sets", duration: 12 },
      { day: 12, name: "Wall Hold", details: "45 sec chest-to-wall hold, 3 sets", duration: 14 },
      { day: 13, name: "Wall Hold", details: "50 sec chest-to-wall hold, 3 sets", duration: 14 },
      { day: 14, name: "Wall Hold", details: "60 sec chest-to-wall hold, 3 sets", duration: 15 },
      { day: 15, name: "Kick-up Practice", details: "10 kick-ups to wall, 3 sets, 60s rest", duration: 12 },
      { day: 16, name: "Kick-up Practice", details: "12 kick-ups to wall, 3 sets, 60s rest", duration: 12 },
      { day: 17, name: "Kick-up Practice", details: "15 kick-ups to wall, 3 sets, 60s rest", duration: 14 },
      { day: 18, name: "Balance Practice", details: "5 one-leg wall holds, 3 sets, 60s rest", duration: 12 },
      { day: 19, name: "Balance Practice", details: "6 one-leg wall holds, 3 sets, 60s rest", duration: 12 },
      { day: 20, name: "Balance Practice", details: "8 one-leg wall holds, 3 sets, 60s rest", duration: 14 },
      { day: 21, name: "Freestanding Attempts", details: "10 freestanding kick-up attempts", duration: 15 },
      { day: 22, name: "Freestanding Attempts", details: "15 freestanding kick-up attempts", duration: 15 },
      { day: 23, name: "Freestanding Attempts", details: "20 freestanding kick-up attempts", duration: 18 },
      { day: 24, name: "Hold Practice", details: "3 sec freestanding hold attempts, 5 sets", duration: 15 },
      { day: 25, name: "Hold Practice", details: "5 sec freestanding hold attempts, 5 sets", duration: 18 },
      { day: 26, name: "Hold Practice", details: "8 sec freestanding hold attempts, 5 sets", duration: 18 },
      { day: 27, name: "Hold Practice", details: "10 sec freestanding hold attempts, 5 sets", duration: 20 },
      { day: 28, name: "Wall Hold", details: "90 sec chest-to-wall hold, 3 sets", duration: 18 },
      { day: 29, name: "Rest Day", details: "Rest Day - prep for final test", duration: 0 },
      { day: 30, name: "Day 30", details: "10 sec freestanding handstand hold", duration: 10 },
    ],
  },
];

// Helper function to get challenge by ID
export function getChallengeById(id: string): Challenge | undefined {
  return challenges.find(challenge => challenge.id === id);
}

// Helper function to get all challenges
export function getAllChallenges(): Challenge[] {
  return challenges;
}